# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "prescription_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique prescription identifier",
                        unique=True,
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("new", "New Prescription"),
                            ("refill", "Refill"),
                            ("change", "Change"),
                            ("cancel", "Cancel"),
                        ],
                        default="new",
                        help_text="Type of prescription",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "drug_name",
                    models.CharField(
                        help_text="Name of prescribed drug", max_length=255
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, help_text="Generic name of drug", max_length=255
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="Drug strength", max_length=50),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        help_text="Dosage form (tablet, capsule, etc.)", max_length=50
                    ),
                ),
                (
                    "ndc_number",
                    models.CharField(
                        blank=True, help_text="National Drug Code", max_length=20
                    ),
                ),
                (
                    "rxnorm_code",
                    models.CharField(
                        blank=True, help_text="RxNorm code", max_length=20
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity to dispense",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        default="tablets", help_text="Unit of quantity", max_length=20
                    ),
                ),
                ("days_supply", models.IntegerField(help_text="Days supply")),
                (
                    "refills",
                    models.IntegerField(
                        default=0,
                        help_text="Number of refills",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "sig_code",
                    models.CharField(blank=True, help_text="Sig code", max_length=10),
                ),
                ("directions", models.TextField(help_text="Directions for use")),
                (
                    "date_prescribed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date prescription was written",
                    ),
                ),
                (
                    "date_sent",
                    models.DateTimeField(
                        blank=True, help_text="Date prescription was sent", null=True
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, help_text="Effective date", null=True),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="Expiration date", null=True
                    ),
                ),
                (
                    "pharmacy_ncpdp",
                    models.CharField(
                        blank=True, help_text="Pharmacy NCPDP ID", max_length=20
                    ),
                ),
                (
                    "pharmacy_name",
                    models.CharField(
                        blank=True, help_text="Pharmacy name", max_length=255
                    ),
                ),
                (
                    "pharmacy_address",
                    models.TextField(blank=True, help_text="Pharmacy address"),
                ),
                (
                    "pharmacy_phone",
                    models.CharField(
                        blank=True, help_text="Pharmacy phone", max_length=20
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True, help_text="ICD-10 diagnosis code", max_length=20
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, help_text="Clinical notes"),
                ),
                (
                    "dispense_as_written",
                    models.BooleanField(
                        default=False, help_text="Dispense as written (DAW)"
                    ),
                ),
                (
                    "controlled_substance",
                    models.BooleanField(
                        default=False, help_text="Is controlled substance"
                    ),
                ),
                (
                    "external_prescription_id",
                    models.CharField(
                        blank=True,
                        help_text="External system prescription ID",
                        max_length=100,
                    ),
                ),
                (
                    "transmission_method",
                    models.CharField(
                        blank=True, help_text="Transmission method", max_length=20
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Response message from pharmacy"
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True, help_text="Response code", max_length=20
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for this prescription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronic_prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        help_text="Prescribing physician",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescribed_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electronic Prescription",
                "verbose_name_plural": "Electronic Prescriptions",
                "db_table": "erx_electronic_prescriptions",
                "ordering": ["-date_prescribed"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyDirectory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ncpdp_id",
                    models.CharField(help_text="NCPDP ID", max_length=20, unique=True),
                ),
                ("name", models.CharField(help_text="Pharmacy name", max_length=255)),
                (
                    "address_line1",
                    models.CharField(help_text="Address line 1", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, help_text="Address line 2", max_length=255
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("state", models.CharField(help_text="State", max_length=2)),
                ("zip_code", models.CharField(help_text="ZIP code", max_length=10)),
                ("phone", models.CharField(help_text="Phone number", max_length=20)),
                (
                    "fax",
                    models.CharField(blank=True, help_text="Fax number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254
                    ),
                ),
                (
                    "accepts_erx",
                    models.BooleanField(
                        default=True, help_text="Accepts electronic prescriptions"
                    ),
                ),
                (
                    "accepts_controlled_substances",
                    models.BooleanField(
                        default=False, help_text="Accepts controlled substances"
                    ),
                ),
                (
                    "hours_operation",
                    models.JSONField(default=dict, help_text="Hours of operation"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is pharmacy active"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, help_text="Last updated"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy",
                "verbose_name_plural": "Pharmacies",
                "db_table": "erx_pharmacy_directory",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("modified", "Modified"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When action was performed",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "old_values",
                    models.JSONField(default=dict, help_text="Previous values"),
                ),
                ("new_values", models.JSONField(default=dict, help_text="New values")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="Related prescription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="erx.electronicprescription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed action",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription History",
                "verbose_name_plural": "Prescription Histories",
                "db_table": "erx_prescription_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionRefill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("refill_number", models.IntegerField(help_text="Refill number")),
                (
                    "date_filled",
                    models.DateTimeField(help_text="Date refill was filled"),
                ),
                (
                    "quantity_dispensed",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity dispensed", max_digits=10
                    ),
                ),
                (
                    "days_supply",
                    models.IntegerField(help_text="Days supply for this refill"),
                ),
                (
                    "pharmacy_ncpdp",
                    models.CharField(
                        blank=True, help_text="Pharmacy NCPDP ID", max_length=20
                    ),
                ),
                (
                    "pharmacist",
                    models.CharField(
                        blank=True, help_text="Dispensing pharmacist", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="Original prescription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_refills",
                        to="erx.electronicprescription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Refill",
                "verbose_name_plural": "Prescription Refills",
                "db_table": "erx_prescription_refills",
                "ordering": ["-date_filled"],
            },
        ),
        migrations.CreateModel(
            name="DrugFormulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug_name",
                    models.CharField(help_text="Name of the drug", max_length=255),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, help_text="Generic name of the drug", max_length=255
                    ),
                ),
                (
                    "ndc_number",
                    models.CharField(
                        blank=True, help_text="National Drug Code number", max_length=20
                    ),
                ),
                (
                    "rxnorm_code",
                    models.CharField(
                        blank=True, help_text="RxNorm code", max_length=20
                    ),
                ),
                (
                    "formulary_status",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("non_preferred", "Non-Preferred"),
                            ("prior_auth", "Prior Authorization Required"),
                            ("step_therapy", "Step Therapy Required"),
                            ("not_covered", "Not Covered"),
                        ],
                        default="preferred",
                        help_text="Status in formulary",
                        max_length=20,
                    ),
                ),
                (
                    "tier_level",
                    models.IntegerField(
                        default=1,
                        help_text="Formulary tier level",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "copay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Copay amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "prior_auth_required",
                    models.BooleanField(
                        default=False, help_text="Prior authorization required"
                    ),
                ),
                (
                    "quantity_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Quantity limit per prescription",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug Formulary",
                "verbose_name_plural": "Drug Formularies",
                "db_table": "erx_drug_formulary",
                "indexes": [
                    models.Index(
                        fields=["drug_name"], name="erx_drug_fo_drug_na_7a9922_idx"
                    ),
                    models.Index(
                        fields=["ndc_number"], name="erx_drug_fo_ndc_num_46f4b3_idx"
                    ),
                    models.Index(
                        fields=["rxnorm_code"], name="erx_drug_fo_rxnorm__a4b643_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug1_name",
                    models.CharField(help_text="First drug name", max_length=255),
                ),
                (
                    "drug2_name",
                    models.CharField(help_text="Second drug name", max_length=255),
                ),
                (
                    "interaction_severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        help_text="Severity of interaction",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_description",
                    models.TextField(help_text="Description of the interaction"),
                ),
                (
                    "clinical_management",
                    models.TextField(
                        blank=True, help_text="Clinical management recommendations"
                    ),
                ),
                (
                    "reference_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of interaction information",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erx_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eRx Drug Interaction",
                "verbose_name_plural": "eRx Drug Interactions",
                "db_table": "erx_drug_interactions",
                "indexes": [
                    models.Index(
                        fields=["drug1_name", "drug2_name"],
                        name="erx_drug_in_drug1_n_a71bf9_idx",
                    ),
                    models.Index(
                        fields=["interaction_severity"],
                        name="erx_drug_in_interac_03f284_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="electronicprescription",
            index=models.Index(
                fields=["patient", "date_prescribed"],
                name="erx_electro_patient_8e8b9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electronicprescription",
            index=models.Index(
                fields=["prescriber", "date_prescribed"],
                name="erx_electro_prescri_6a09bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="electronicprescription",
            index=models.Index(fields=["status"], name="erx_electro_status_202f05_idx"),
        ),
        migrations.AddIndex(
            model_name="electronicprescription",
            index=models.Index(
                fields=["prescription_id"], name="erx_electro_prescri_8a23d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacydirectory",
            index=models.Index(
                fields=["ncpdp_id"], name="erx_pharmac_ncpdp_i_8e222d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacydirectory",
            index=models.Index(fields=["name"], name="erx_pharmac_name_7649ca_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacydirectory",
            index=models.Index(
                fields=["city", "state"], name="erx_pharmac_city_b2775b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionhistory",
            index=models.Index(
                fields=["prescription", "timestamp"],
                name="erx_prescri_prescri_465da4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionhistory",
            index=models.Index(
                fields=["user", "timestamp"], name="erx_prescri_user_id_895252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionrefill",
            index=models.Index(
                fields=["prescription", "refill_number"],
                name="erx_prescri_prescri_aeae35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionrefill",
            index=models.Index(
                fields=["date_filled"], name="erx_prescri_date_fi_0c551f_idx"
            ),
        ),
    ]
