# Generated by Django 5.2.4 on 2025-07-18 13:31

import communications.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("ALL_USERS", "所有用戶"),
                            ("DEPARTMENT", "部門"),
                            ("ROLE", "角色"),
                            ("CUSTOM", "自訂清單"),
                            ("PATIENTS", "患者"),
                            ("STAFF", "員工"),
                        ],
                        max_length=20,
                        verbose_name="接收者類型",
                    ),
                ),
                (
                    "recipient_filter",
                    models.JSONField(blank=True, default=dict, verbose_name="接收者篩選條件"),
                ),
                (
                    "send_via_app",
                    models.BooleanField(default=True, verbose_name="應用內通知"),
                ),
                (
                    "send_via_email",
                    models.BooleanField(default=False, verbose_name="郵件通知"),
                ),
                (
                    "send_via_sms",
                    models.BooleanField(default=False, verbose_name="簡訊通知"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="排程時間"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("SCHEDULED", "已排程"),
                            ("SENDING", "發送中"),
                            ("SENT", "已發送"),
                            ("FAILED", "發送失敗"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="發送時間"),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(default=0, verbose_name="總接收者數"),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(default=0, verbose_name="已發送數"),
                ),
                (
                    "delivered_count",
                    models.PositiveIntegerField(default=0, verbose_name="已送達數"),
                ),
                (
                    "read_count",
                    models.PositiveIntegerField(default=0, verbose_name="已閱讀數"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="失敗數"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次訊息",
                "verbose_name_plural": "批次訊息",
                "db_table": "communications_bulk_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkMessageRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待發送"),
                            ("SENDING", "發送中"),
                            ("SENT", "已發送"),
                            ("DELIVERED", "已送達"),
                            ("READ", "已閱讀"),
                            ("FAILED", "發送失敗"),
                            ("BOUNCED", "退回"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="應用狀態",
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待發送"),
                            ("SENDING", "發送中"),
                            ("SENT", "已發送"),
                            ("DELIVERED", "已送達"),
                            ("READ", "已閱讀"),
                            ("FAILED", "發送失敗"),
                            ("BOUNCED", "退回"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="郵件狀態",
                    ),
                ),
                (
                    "sms_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待發送"),
                            ("SENDING", "發送中"),
                            ("SENT", "已發送"),
                            ("DELIVERED", "已送達"),
                            ("READ", "已閱讀"),
                            ("FAILED", "發送失敗"),
                            ("BOUNCED", "退回"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="簡訊狀態",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="發送時間"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="送達時間"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="閱讀時間"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="錯誤訊息"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="重試次數"),
                ),
                (
                    "bulk_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communications.bulkmessage",
                        verbose_name="批次訊息",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次訊息接收者",
                "verbose_name_plural": "批次訊息接收者",
                "db_table": "communications_bulk_message_recipient",
            },
        ),
        migrations.AddField(
            model_name="bulkmessage",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_bulk_messages",
                through="communications.BulkMessageRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收者",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "文字訊息"),
                            ("FILE", "檔案訊息"),
                            ("IMAGE", "圖片訊息"),
                            ("VOICE", "語音訊息"),
                            ("VIDEO", "視訊訊息"),
                            ("SYSTEM", "系統訊息"),
                            ("NOTIFICATION", "通知訊息"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="訊息類型",
                    ),
                ),
                ("content", models.TextField(verbose_name="訊息內容")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發送時間"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="編輯時間"),
                ),
                ("is_edited", models.BooleanField(default=False, verbose_name="是否已編輯")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已刪除"),
                ),
                ("is_urgent", models.BooleanField(default=False, verbose_name="緊急訊息")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="重要訊息"),
                ),
                (
                    "requires_response",
                    models.BooleanField(default=False, verbose_name="需要回應"),
                ),
                (
                    "response_deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="回應期限"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP位址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用戶代理"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=True, verbose_name="是否加密"),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="communications.message",
                        verbose_name="回覆訊息",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息",
                "verbose_name_plural": "訊息",
                "db_table": "communications_message",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=communications.models.message_attachment_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "svg",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "zip",
                                    "rar",
                                    "7z",
                                    "txt",
                                    "csv",
                                ]
                            )
                        ],
                        verbose_name="附件檔案",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始檔名"),
                ),
                ("file_size", models.PositiveIntegerField(verbose_name="檔案大小")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME類型")),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "文件"),
                            ("IMAGE", "圖片"),
                            ("AUDIO", "音訊"),
                            ("VIDEO", "視訊"),
                            ("ARCHIVE", "壓縮檔"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="附件類型",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                ("is_scanned", models.BooleanField(default=False, verbose_name="已掃描")),
                (
                    "scan_result",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="掃描結果"
                    ),
                ),
                ("is_safe", models.BooleanField(default=True, verbose_name="是否安全")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="communications.message",
                        verbose_name="所屬訊息",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息附件",
                "verbose_name_plural": "訊息附件",
                "db_table": "communications_message_attachment",
            },
        ),
        migrations.CreateModel(
            name="MessageChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="頻道名稱")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="頻道描述"),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "直接訊息"),
                            ("GROUP", "群組訊息"),
                            ("BROADCAST", "廣播訊息"),
                            ("DEPARTMENT", "部門訊息"),
                            ("EMERGENCY", "緊急訊息"),
                        ],
                        default="DIRECT",
                        max_length=20,
                        verbose_name="頻道類型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="是否封存"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後活動時間"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=True, verbose_name="是否加密"),
                ),
                (
                    "require_approval",
                    models.BooleanField(default=False, verbose_name="需要審核"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最大參與者數"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_channels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息頻道",
                "verbose_name_plural": "訊息頻道",
                "db_table": "communications_message_channel",
            },
        ),
        migrations.CreateModel(
            name="MessageParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "成員"),
                            ("MODERATOR", "版主"),
                            ("ADMIN", "管理員"),
                            ("OBSERVER", "觀察者"),
                        ],
                        default="MEMBER",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "活躍"),
                            ("INACTIVE", "非活躍"),
                            ("MUTED", "靜音"),
                            ("BANNED", "封禁"),
                            ("LEFT", "已離開"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入時間"),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後閱讀時間"),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, verbose_name="啟用通知"),
                ),
                (
                    "can_send_messages",
                    models.BooleanField(default=True, verbose_name="可發送訊息"),
                ),
                (
                    "can_upload_files",
                    models.BooleanField(default=True, verbose_name="可上傳檔案"),
                ),
                (
                    "can_invite_users",
                    models.BooleanField(default=False, verbose_name="可邀請用戶"),
                ),
                (
                    "can_moderate",
                    models.BooleanField(default=False, verbose_name="可管理"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="communications.messagechannel",
                        verbose_name="所屬頻道",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息參與者",
                "verbose_name_plural": "訊息參與者",
                "db_table": "communications_message_participant",
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("LIKE", "👍"),
                            ("LOVE", "❤️"),
                            ("LAUGH", "😄"),
                            ("SURPRISE", "😮"),
                            ("SAD", "😢"),
                            ("ANGRY", "😡"),
                            ("THUMBS_DOWN", "👎"),
                        ],
                        max_length=20,
                        verbose_name="回應類型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="communications.message",
                        verbose_name="所屬訊息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息回應",
                "verbose_name_plural": "訊息回應",
                "db_table": "communications_message_reaction",
            },
        ),
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="閱讀時間"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="communications.message",
                        verbose_name="所屬訊息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息已讀回條",
                "verbose_name_plural": "訊息已讀回條",
                "db_table": "communications_message_read_receipt",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名稱")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模板描述"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "歡迎訊息"),
                            ("REMINDER", "提醒訊息"),
                            ("NOTIFICATION", "通知訊息"),
                            ("APPOINTMENT", "預約訊息"),
                            ("BILLING", "帳單訊息"),
                            ("EMERGENCY", "緊急訊息"),
                            ("CUSTOM", "自訂訊息"),
                        ],
                        max_length=20,
                        verbose_name="模板類型",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(max_length=500, verbose_name="主題模板"),
                ),
                ("content_template", models.TextField(verbose_name="內容模板")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "is_system_template",
                    models.BooleanField(default=False, verbose_name="系統模板"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次數"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後使用時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息模板",
                "verbose_name_plural": "訊息模板",
                "db_table": "communications_message_template",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="主題")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始時間"),
                ),
                (
                    "last_reply_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後回覆時間"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "低"),
                            ("NORMAL", "普通"),
                            ("HIGH", "高"),
                            ("URGENT", "緊急"),
                            ("CRITICAL", "危急"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "進行中"),
                            ("RESOLVED", "已解決"),
                            ("CLOSED", "已關閉"),
                            ("ARCHIVED", "已封存"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="是否置頂")),
                (
                    "message_count",
                    models.PositiveIntegerField(default=0, verbose_name="訊息數量"),
                ),
                (
                    "participant_count",
                    models.PositiveIntegerField(default=0, verbose_name="參與者數量"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="appointments.appointment",
                        verbose_name="相關預約",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="communications.messagechannel",
                        verbose_name="所屬頻道",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="medical_records.medicalrecord",
                        verbose_name="相關醫療記錄",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="patients.patient",
                        verbose_name="相關患者",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發起者",
                    ),
                ),
            ],
            options={
                "verbose_name": "訊息串",
                "verbose_name_plural": "訊息串",
                "db_table": "communications_message_thread",
                "ordering": ["-is_pinned", "-last_reply_at", "-started_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communications.messagethread",
                verbose_name="所屬訊息串",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "新訊息"),
                            ("MENTION", "提及"),
                            ("REPLY", "回覆"),
                            ("REACTION", "回應"),
                            ("INVITATION", "邀請"),
                            ("SYSTEM", "系統通知"),
                            ("REMINDER", "提醒"),
                        ],
                        max_length=20,
                        verbose_name="通知類型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知標題")),
                ("content", models.TextField(verbose_name="通知內容")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "低"),
                            ("NORMAL", "普通"),
                            ("HIGH", "高"),
                            ("URGENT", "緊急"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="優先級",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已讀")),
                ("is_sent", models.BooleanField(default=False, verbose_name="是否已發送")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="閱讀時間"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="發送時間"),
                ),
                ("send_email", models.BooleanField(default=False, verbose_name="發送郵件")),
                ("send_sms", models.BooleanField(default=False, verbose_name="發送簡訊")),
                ("send_push", models.BooleanField(default=True, verbose_name="推播通知")),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="communications.messagechannel",
                        verbose_name="相關頻道",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="communications.message",
                        verbose_name="相關訊息",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="communications.messagethread",
                        verbose_name="相關訊息串",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "communications_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bulkmessagerecipient",
            index=models.Index(
                fields=["bulk_message", "app_status"],
                name="communicati_bulk_me_bde46c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmessagerecipient",
            index=models.Index(
                fields=["recipient"], name="communicati_recipie_148a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmessagerecipient",
            index=models.Index(
                fields=["sent_at"], name="communicati_sent_at_4536db_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bulkmessagerecipient",
            unique_together={("bulk_message", "recipient")},
        ),
        migrations.AddIndex(
            model_name="bulkmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="communicati_sender__ea0b5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkmessage",
            index=models.Index(fields=["status"], name="communicati_status_41df1d_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkmessage",
            index=models.Index(
                fields=["scheduled_at"], name="communicati_schedul_f44e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["message"], name="communicati_message_1386fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["attachment_type"], name="communicati_attachm_e8db98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["uploaded_at"], name="communicati_uploade_aa8e0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagechannel",
            index=models.Index(
                fields=["channel_type", "is_active"],
                name="communicati_channel_c04609_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagechannel",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="communicati_created_9a9f3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagechannel",
            index=models.Index(
                fields=["last_activity"], name="communicati_last_ac_66f315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(
                fields=["channel", "status"], name="communicati_channel_94b7d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(
                fields=["user", "joined_at"], name="communicati_user_id_8be59e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(fields=["role"], name="communicati_role_133c85_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messageparticipant",
            unique_together={("channel", "user")},
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "reaction_type"],
                name="communicati_message_3fd58e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["user"], name="communicati_user_id_f52c3c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "reaction_type")},
        ),
        migrations.AddIndex(
            model_name="messagereadreceipt",
            index=models.Index(
                fields=["message"], name="communicati_message_fe6bf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadreceipt",
            index=models.Index(
                fields=["user", "read_at"], name="communicati_user_id_9ae1b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadreceipt",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="communicati_templat_946e75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["created_by"], name="communicati_created_4337df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["usage_count"], name="communicati_usage_c_d11bcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["channel", "status"], name="communicati_channel_da87e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["started_by", "started_at"],
                name="communicati_started_57f6d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["priority", "status"], name="communicati_priorit_ea0435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["patient"], name="communicati_patient_596da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["last_reply_at"], name="communicati_last_re_d15ecb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "sent_at"], name="communicati_thread__6b0372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "sent_at"], name="communicati_sender__791563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="communicati_message_4a1d97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_urgent", "is_important"],
                name="communicati_is_urge_8c4d87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["requires_response", "response_deadline"],
                name="communicati_require_7f4583_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="communicati_recipie_dd2f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="communicati_notific_8e3688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "created_at"], name="communicati_priorit_167962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="communicati_created_fb7216_idx"
            ),
        ),
    ]
