# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "protocol_type",
                    models.CharField(
                        choices=[
                            ("treatment", "Treatment Protocol"),
                            ("diagnostic", "Diagnostic Protocol"),
                            ("prevention", "Prevention Protocol"),
                            ("emergency", "Emergency Protocol"),
                            ("chronic_care", "Chronic Care Protocol"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Ordered list of protocol steps"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions for protocol activation"
                    ),
                ),
                ("guideline_source", models.CharField(blank=True, max_length=200)),
                ("evidence_level", models.CharField(blank=True, max_length=20)),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("code", "version")},
            },
        ),
        migrations.CreateModel(
            name="ClinicalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("medication_alert", "Medication Alert"),
                            ("allergy_check", "Allergy Check"),
                            ("lab_alert", "Laboratory Alert"),
                            ("interaction_check", "Drug Interaction Check"),
                            ("contraindication", "Contraindication"),
                            ("preventive_care", "Preventive Care Reminder"),
                            ("chronic_care", "Chronic Care Management"),
                            ("age_based", "Age-Based Reminder"),
                            ("diagnosis_based", "Diagnosis-Based Alert"),
                            ("procedure_alert", "Procedure Alert"),
                            ("vital_signs", "Vital Signs Alert"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "condition_logic",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration defining when this rule triggers",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("alert", "Show Alert"),
                            ("warning", "Show Warning"),
                            ("block", "Block Action"),
                            ("reminder", "Send Reminder"),
                            ("notification", "Send Notification"),
                            ("order_set", "Suggest Order Set"),
                            ("protocol", "Activate Protocol"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration defining what action to take",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "is_real_time",
                    models.BooleanField(
                        default=True, help_text="Execute rule in real-time"
                    ),
                ),
                (
                    "check_frequency_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For non-real-time rules, how often to check (in hours)",
                        null=True,
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence_level",
                    models.CharField(
                        blank=True,
                        help_text="Evidence quality (A, B, C)",
                        max_length=20,
                    ),
                ),
                (
                    "reference_url",
                    models.URLField(
                        blank=True, help_text="Link to clinical guidelines"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        default=dict, help_text="Data that triggered this alert"
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        default=list,
                        help_text="Recommended actions to address the alert",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("dismissed", "Dismissed"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgment_note", models.TextField(blank=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_alerts",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="clinical_decision_support.clinicalrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at", "-alert_level"],
            },
        ),
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug_1",
                    models.CharField(
                        help_text="First drug name or code", max_length=200
                    ),
                ),
                (
                    "drug_2",
                    models.CharField(
                        help_text="Second drug name or code", max_length=200
                    ),
                ),
                ("interaction_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        max_length=15,
                    ),
                ),
                ("mechanism", models.TextField(help_text="How the interaction occurs")),
                (
                    "clinical_effect",
                    models.TextField(help_text="Clinical effects of the interaction"),
                ),
                (
                    "management",
                    models.TextField(help_text="How to manage the interaction"),
                ),
                ("evidence_level", models.CharField(blank=True, max_length=20)),
                ("reference_source", models.CharField(blank=True, max_length=200)),
                ("reference_url", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["drug_1", "drug_2"],
            },
        ),
        migrations.CreateModel(
            name="PreventiveCareReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("immunization", "Immunization"),
                            ("lifestyle", "Lifestyle Counseling"),
                            ("medication", "Preventive Medication"),
                            ("followup", "Follow-up Care"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("target_age_min", models.PositiveIntegerField(blank=True, null=True)),
                ("target_age_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                    ),
                ),
                (
                    "target_conditions",
                    models.JSONField(
                        default=list, help_text="ICD-10 codes or condition names"
                    ),
                ),
                (
                    "interval_months",
                    models.PositiveIntegerField(
                        help_text="Reminder interval in months"
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days before due date to remind"
                    ),
                ),
                ("guideline_source", models.CharField(blank=True, max_length=200)),
                ("evidence_grade", models.CharField(blank=True, max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("due_date", models.DateField()),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("due", "Due"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                            ("dismissed", "Dismissed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preventive_care",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinical_decision_support.preventivecarereminder",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                (
                    "step_results",
                    models.JSONField(
                        default=dict, help_text="Results from each protocol step"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_executions",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_executions",
                        to="patients.patient",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="clinical_decision_support.clinicalprotocol",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="started_protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rule Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="clinicalrule",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="clinical_decision_support.rulecategory",
            ),
        ),
        migrations.CreateModel(
            name="RuleExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        help_text="Execution time in milliseconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input data used for rule evaluation"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        default=dict, help_text="Output from rule execution"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("condition_met", models.BooleanField(default=False)),
                ("alert_generated", models.BooleanField(default=False)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinical_decision_support.clinicalalert",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_executions",
                        to="patients.patient",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="clinical_decision_support.clinicalrule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clinicalalert",
            index=models.Index(
                fields=["patient", "status"], name="clinical_de_patient_095454_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalalert",
            index=models.Index(
                fields=["rule", "status"], name="clinical_de_rule_id_f109ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalalert",
            index=models.Index(
                fields=["triggered_at"], name="clinical_de_trigger_e80afd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(fields=["drug_1"], name="clinical_de_drug_1_b5f9d1_idx"),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(fields=["drug_2"], name="clinical_de_drug_2_6cc475_idx"),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["severity"], name="clinical_de_severit_2b77fb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("drug_1", "drug_2")},
        ),
        migrations.AddIndex(
            model_name="patientreminder",
            index=models.Index(
                fields=["patient", "status"], name="clinical_de_patient_a7cb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientreminder",
            index=models.Index(
                fields=["due_date", "status"], name="clinical_de_due_dat_216b93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientreminder",
            unique_together={("patient", "preventive_care", "due_date")},
        ),
        migrations.AddIndex(
            model_name="protocolexecution",
            index=models.Index(
                fields=["patient", "status"], name="clinical_de_patient_6803b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protocolexecution",
            index=models.Index(
                fields=["protocol", "status"], name="clinical_de_protoco_615a60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clinicalrule",
            unique_together={("code", "version")},
        ),
        migrations.AddIndex(
            model_name="ruleexecution",
            index=models.Index(
                fields=["rule", "executed_at"], name="clinical_de_rule_id_2af683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleexecution",
            index=models.Index(
                fields=["patient", "executed_at"], name="clinical_de_patient_b583e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleexecution",
            index=models.Index(fields=["status"], name="clinical_de_status_d19ebf_idx"),
        ),
    ]
