# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the therapy group", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the therapy group"
                    ),
                ),
                (
                    "therapy_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Therapy"),
                            ("group", "Group Therapy"),
                            ("family", "Family Therapy"),
                            ("couples", "Couples Therapy"),
                            ("cognitive", "Cognitive Behavioral Therapy"),
                            ("psychodynamic", "Psychodynamic Therapy"),
                            ("humanistic", "Humanistic Therapy"),
                            ("behavioral", "Behavioral Therapy"),
                            ("other", "Other"),
                        ],
                        default="group",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the therapy group"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date of the therapy group", null=True
                    ),
                ),
                (
                    "session_duration",
                    models.IntegerField(
                        help_text="Duration of each session in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of participants",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location where therapy takes place",
                        max_length=200,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, help_text="Room number or identifier", max_length=50
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True, help_text="Contact information for the group"
                    ),
                ),
                (
                    "treatment_goals",
                    models.TextField(
                        blank=True, help_text="Treatment goals for the group"
                    ),
                ),
                (
                    "inclusion_criteria",
                    models.TextField(
                        blank=True, help_text="Criteria for group inclusion"
                    ),
                ),
                (
                    "exclusion_criteria",
                    models.TextField(
                        blank=True, help_text="Criteria for group exclusion"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Administrative notes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "co_therapists",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Co-therapists for this group",
                        related_name="co_therapy_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_therapist",
                    models.ForeignKey(
                        help_text="Primary therapist for this group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_therapy_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Therapy Group",
                "verbose_name_plural": "Therapy Groups",
                "db_table": "therapy_groups",
                "ordering": ["name", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="TherapyGroupParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "presenting_concerns",
                    models.TextField(
                        blank=True, help_text="Patient's presenting concerns"
                    ),
                ),
                (
                    "treatment_goals",
                    models.TextField(
                        blank=True, help_text="Individual treatment goals"
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, help_text="Progress notes"),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("referral_source", models.CharField(blank=True, max_length=200)),
                ("sessions_attended", models.IntegerField(default=0)),
                ("sessions_missed", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="therapy_groups.therapygroup",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_groups",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Therapy Group Participant",
                "verbose_name_plural": "Therapy Group Participants",
                "db_table": "therapy_group_participants",
                "ordering": ["enrollment_date"],
                "unique_together": {("group", "patient")},
            },
        ),
        migrations.CreateModel(
            name="TherapySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session_number",
                    models.IntegerField(help_text="Session number in the series"),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "topic",
                    models.CharField(
                        blank=True, help_text="Session topic or theme", max_length=200
                    ),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, help_text="Session objectives"),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True, help_text="Activities and interventions used"
                    ),
                ),
                (
                    "session_notes",
                    models.TextField(
                        blank=True, help_text="Clinical notes from the session"
                    ),
                ),
                (
                    "homework_assigned",
                    models.TextField(
                        blank=True, help_text="Homework or tasks assigned"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "outcomes",
                    models.TextField(
                        blank=True, help_text="Session outcomes and observations"
                    ),
                ),
                (
                    "co_therapists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_therapy_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="therapy_groups.therapygroup",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Therapy Session",
                "verbose_name_plural": "Therapy Sessions",
                "db_table": "therapy_sessions",
                "ordering": ["scheduled_date", "scheduled_time"],
                "unique_together": {("group", "session_number")},
            },
        ),
        migrations.CreateModel(
            name="TherapyGroupNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress Note"),
                            ("incident", "Incident Report"),
                            ("assessment", "Assessment"),
                            ("treatment_plan", "Treatment Plan"),
                            ("discharge", "Discharge Summary"),
                            ("other", "Other"),
                        ],
                        default="progress",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "observations",
                    models.TextField(blank=True, help_text="Clinical observations"),
                ),
                (
                    "interventions",
                    models.TextField(blank=True, help_text="Interventions used"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Patient response to interventions"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True, help_text="Treatment plan or next steps"
                    ),
                ),
                ("is_confidential", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="therapy_groups.therapygroup",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="therapy_groups.therapygroupparticipant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="therapy_groups.therapysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Therapy Group Note",
                "verbose_name_plural": "Therapy Group Notes",
                "db_table": "therapy_group_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("left_early", "Left Early"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about attendance"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="therapy_groups.therapygroupparticipant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="therapy_groups.therapysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Attendance",
                "verbose_name_plural": "Session Attendance",
                "db_table": "session_attendance",
                "ordering": [
                    "session__scheduled_date",
                    "participant__patient__last_name",
                ],
                "unique_together": {("session", "participant")},
            },
        ),
    ]
