[pytest]
DJANGO_SETTINGS_MODULE = medical_system.settings
testpaths =
    tests
    apps/clinical/patients
    apps/clinical/health_screening
python_files = test_*.py tests.py
norecursedirs = archive .git venv frontend node_modules
