# Generated by Django 5.2.4 on 2025-09-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'health_screening',
            "0002_cardiovascularriskindex_ascvd_10_year_risk_men_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="healthscreening",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="laboratoryresults",
            name="serum_creatinine_mgdl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="血清肌酸酐(mg/dL)",
            ),
        ),
        migrations.AlterField(
            model_name="lifestylequestionnaire",
            name="diet_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "無蔬果"),
                    ("1", "1份蔬果"),
                    ("2", "2份蔬果"),
                    ("3", "3份蔬果"),
                    ("4", "4份蔬果"),
                    ("5", "5份蔬果"),
                    ("6", "6份蔬果"),
                    ("7", "7份蔬果"),
                    ("8+", "8份以上蔬果"),
                    ("excellent", "優秀"),
                    ("good", "良好"),
                    ("fair", "普通"),
                    ("poor", "不佳"),
                ],
                max_length=20,
                null=True,
                verbose_name="飲食評分",
            ),
        ),
        migrations.AlterField(
            model_name="lifestylequestionnaire",
            name="drinking_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "不飲酒"),
                    ("never", "從不飲酒"),
                    ("rarely", "很少飲酒"),
                    ("sometimes", "偶爾飲酒"),
                    ("occasionally", "偶爾飲酒"),
                    ("regularly", "規律飲酒"),
                    ("frequently", "經常飲酒"),
                    ("social", "社交飲酒"),
                    ("moderate", "適度飲酒"),
                    ("heavy", "重度飲酒"),
                    ("daily", "每日飲酒"),
                ],
                max_length=20,
                null=True,
                verbose_name="飲酒狀況",
            ),
        ),
        migrations.AlterField(
            model_name="lifestylequestionnaire",
            name="exercise_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "不活動"),
                    ("1", "輕度運動"),
                    ("2", "中度運動"),
                    ("3", "重度運動"),
                    ("regularly", "規律運動"),
                    ("sometimes", "偶爾運動"),
                    ("rarely", "很少運動"),
                    ("never", "從不運動"),
                ],
                max_length=20,
                null=True,
                verbose_name="運動評分",
            ),
        ),
    ]
