# Generated by Django 5.0.8 on 2026-01-14 04:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_screening', '0004_add_detailed_lifestyle_fields'),
        ('patients', '0005_careteammember_familyhealthhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestylequestionnaire',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lifestylequestionnaire',
            name='health_screening',
        ),
        migrations.RemoveField(
            model_name='lifestylequestionnaire',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='health_screening',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='healthscreening',
            options={'verbose_name': '就診/健康檢查'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryresults',
            options={'verbose_name': '實驗室檢驗'},
        ),
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'verbose_name': '生命體徵'},
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='height_cm',
            new_name='body_height',
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='weight_kg',
            new_name='body_weight',
        ),
        migrations.RemoveField(
            model_name='healthscreening',
            name='age_at_screening',
        ),
        migrations.RemoveField(
            model_name='healthscreening',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='healthscreening',
            name='screening_type',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='albumin_gdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='albumin_globulin_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='alt_gpt_ul',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ast_alt_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ast_got_ul',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ast_uln_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='atherogenic_index_plasma',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='egdr',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='estimated_avg_glucose_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='fasting_glucose_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ggt_ul',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='globulin_gdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='hba1c_percent',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='hdl_cholesterol_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='homa_ir',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='homocysteine_umol_l',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='hs_crp_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='impaired_fasting_glucose',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='insulin_uiu_ml',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ldl_cholesterol_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='ldl_hdl_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='monocyte_absolute',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='monocyte_percent',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='non_hdl_cholesterol_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='non_hdl_hdl_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='platelet_count',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='plp_cholesterol_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='rbc_count',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='rdw_cv_percent',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='serum_creatinine_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='tc_hdl_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='tg_hdl_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='total_cholesterol_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='total_protein_gdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='triglyceride_glucose_index',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='triglycerides_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='tyg_bmi',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='uric_acid_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='urine_albumin_creatinine_ratio',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='urine_albumin_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='urine_creatinine_mgdl',
        ),
        migrations.RemoveField(
            model_name='laboratoryresults',
            name='wbc_count',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='central_diastolic_bp_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='central_systolic_bp_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='chest_circumference_cm',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='diastolic_bp_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='hip_circumference_cm',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='mean_arterial_pressure_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='neck_circumference_cm',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='pulse_pressure_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='pulse_rate_bpm',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='systolic_bp_mmhg',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='waist_circumference_cm',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='waist_height_ratio',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='waist_hip_ratio',
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='encounter_disposition',
            field=models.CharField(blank=True, max_length=200, verbose_name='就診處置'),
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='encounter_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='就診識別碼'),
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='encounter_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='就診地點'),
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='encounter_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='就診時間'),
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='encounter_type',
            field=models.CharField(default='annual_physical', max_length=100, verbose_name='就診類型'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='result_interpretation',
            field=models.CharField(blank=True, max_length=100, verbose_name='結果解釋'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='result_reference_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='參考範圍'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='result_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='結果狀態 (Status)'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='result_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='單位 (Unit)'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='specimen_condition',
            field=models.CharField(blank=True, max_length=200, verbose_name='檢體狀況接受度'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='specimen_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='檢體識別碼'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='specimen_source_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='檢體來源部位'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='檢體類型'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='test_name',
            field=models.CharField(default='Unknown Test', max_length=200, verbose_name='檢測項目 (Tests)'),
        ),
        migrations.AddField(
            model_name='laboratoryresults',
            name='value_result',
            field=models.CharField(default='Pending', max_length=100, verbose_name='數值/結果 (Values/Results)'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='average_blood_pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均血壓'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='bmi_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI百分位數 (2-20歲)'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體溫'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='diastolic_blood_pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='舒張壓'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='head_circumference_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='頭圍百分位數 (0-36月)'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='心率'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='inhaled_oxygen_concentration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='吸入氧氣濃度'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='pulse_oximetry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='血氧飽和度'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='呼吸頻率'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='systolic_blood_pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='收縮壓'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='weight_for_length_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身長體重百分位數 (0-24月)'),
        ),
        migrations.AlterField(
            model_name='healthscreening',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='laboratoryresults',
            name='health_screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='health_screening.healthscreening'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='health_screening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='health_screening.healthscreening'),
        ),
        migrations.CreateModel(
            name='ClinicalTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_name', models.CharField(max_length=200, verbose_name='測試名稱')),
                ('result_value', models.CharField(max_length=200, verbose_name='結果數值/報告')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='測試日期')),
                ('interpretation', models.TextField(blank=True, verbose_name='結果解釋')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('health_screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tests', to='health_screening.healthscreening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '臨床測試結果',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticImagingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imaging_test_name', models.CharField(max_length=200, verbose_name='影像檢查名稱')),
                ('modality', models.CharField(max_length=100, verbose_name='檢查類別 (Modality)')),
                ('findings', models.TextField(blank=True, verbose_name='發現 (Findings)')),
                ('report_text', models.TextField(verbose_name='報告內容')),
                ('image_url', models.URLField(blank=True, verbose_name='影像連結')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='檢查日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('health_screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='health_screening.healthscreening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '診斷影像報告',
            },
        ),
        migrations.CreateModel(
            name='HealthStatusAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_concerns', models.TextField(blank=True, default='', verbose_name='健康疑慮')),
                ('functional_status', models.TextField(blank=True, default='', verbose_name='功能狀態')),
                ('disability_status', models.TextField(blank=True, default='', verbose_name='殘疾狀態')),
                ('mental_cognitive_status', models.TextField(blank=True, default='', verbose_name='精神/認知狀態')),
                ('pregnancy_status', models.CharField(blank=True, default='', max_length=100, verbose_name='懷孕狀態')),
                ('alcohol_use', models.TextField(blank=True, default='', verbose_name='飲酒情況')),
                ('substance_use', models.TextField(blank=True, default='', verbose_name='物質使用')),
                ('physical_activity', models.TextField(blank=True, default='', verbose_name='體育活動')),
                ('sdoh_assessment', models.TextField(blank=True, default='', verbose_name='SDOH 評估')),
                ('smoking_status', models.CharField(blank=True, default='', max_length=100, verbose_name='吸菸狀態')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('health_screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='health_screening.healthscreening')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康狀態評估',
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='疫苗名稱')),
                ('administration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='接種日期')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='批號 (Lot Number)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '免疫接種',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('problem_name', models.CharField(max_length=200, verbose_name='問題名稱')),
                ('sdoh_problem', models.BooleanField(default=False, verbose_name='是否為 SDOH 問題')),
                ('date_of_onset', models.DateField(blank=True, null=True, verbose_name='發病日期')),
                ('date_of_diagnosis', models.DateField(blank=True, null=True, verbose_name='診斷日期')),
                ('date_of_resolution', models.DateField(blank=True, null=True, verbose_name='解決日期')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='狀態')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康問題',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('procedure_name', models.CharField(max_length=200, verbose_name='處置名稱')),
                ('performance_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='執行時間')),
                ('sdoh_intervention', models.TextField(blank=True, verbose_name='SDOH 介入')),
                ('reason_for_referral', models.TextField(blank=True, verbose_name='轉診原因')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '醫療處置',
            },
        ),
        migrations.DeleteModel(
            name='CardiovascularRiskIndex',
        ),
        migrations.DeleteModel(
            name='LifestyleQuestionnaire',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
