# Generated by Django 5.0.8 on 2026-04-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_screening', '0005_remove_lifestylequestionnaire_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinicaltestresult',
            table='health_screening_clinicaltestresult',
        ),
        migrations.AlterModelTable(
            name='diagnosticimagingresult',
            table='health_screening_diagnosticimagingresult',
        ),
        migrations.AlterModelTable(
            name='healthscreening',
            table='health_screening_healthscreening',
        ),
        migrations.AlterModelTable(
            name='healthstatusassessment',
            table='health_screening_healthstatusassessment',
        ),
        migrations.AlterModelTable(
            name='immunization',
            table='health_screening_immunization',
        ),
        migrations.AlterModelTable(
            name='laboratoryresults',
            table='health_screening_laboratoryresults',
        ),
        migrations.AlterModelTable(
            name='problem',
            table='health_screening_problem',
        ),
        migrations.AlterModelTable(
            name='procedure',
            table='health_screening_procedure',
        ),
        migrations.AlterModelTable(
            name='vitalsigns',
            table='health_screening_vitalsigns',
        ),
    ]
