# Generated by Django 5.0.8 on 2026-06-10 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_integration', '0002_alter_uscdidataelement_uscdi_class'),
        ('health_screening', '0006_alter_clinicaltestresult_table_and_more'),
        ('patients', '0006_alter_advancedirective_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('algorithm_scope', models.CharField(default='comprehensive', max_length=100)),
                ('model_version', models.CharField(default='risk-engine-v1', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('health_screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessment_runs', to='health_screening.healthscreening')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment_runs', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessment_run',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=150)),
                ('risk_value', models.CharField(blank=True, default='', max_length=50)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('risk_level', models.CharField(blank=True, default='', max_length=50)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fhir_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_results', to='fhir_integration.fhirresource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='health_screening.riskassessmentrun')),
            ],
            options={
                'db_table': 'risk_assessment_result',
            },
        ),
        migrations.CreateModel(
            name='RiskRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(default='routine', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('recommendation', models.TextField()),
                ('follow_up_interval_days', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='health_screening.riskassessmentrun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_recommendation',
            },
        ),
        migrations.AddIndex(
            model_name='riskassessmentrun',
            index=models.Index(fields=['patient', '-generated_at'], name='risk_assess_patient_db54e1_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessmentrun',
            index=models.Index(fields=['status'], name='risk_assess_status_8dc4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessmentresult',
            index=models.Index(fields=['algorithm', 'outcome'], name='risk_assess_algorit_e55588_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecommendation',
            index=models.Index(fields=['priority'], name='risk_recomm_priorit_cb25e3_idx'),
        ),
    ]
