# Generated by Django 5.0.8 on 2026-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_screening', '0008_aianalysisjob_aianalysisresult_caretask_consent_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='aianalysisjob',
            table_comment='疾病風險判讀工作；保存分析類型、模型版本、輸入快照與執行狀態。FHIR 對應：ServiceRequest、Provenance。',
        ),
        migrations.AlterModelTableComment(
            name='aianalysisresult',
            table_comment='疾病風險判讀結果；保存信心分數、解釋、建議與醫師審核狀態。FHIR 對應：RiskAssessment、Observation、DiagnosticReport、DocumentReference。',
        ),
        migrations.AlterModelTableComment(
            name='questionnaireresponse',
            table_comment='問卷填答結果；保存完整 response_json 與 score_json 供疾病風險判讀與 FHIR 投影。FHIR 對應：QuestionnaireResponse、Observation survey。',
        ),
    ]
