# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSystemVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "system_name",
                    models.CharField(
                        choices=[
                            ("icd10", "ICD-10"),
                            ("icd9", "ICD-9"),
                            ("cpt", "CPT"),
                            ("snomed", "SNOMED CT"),
                            ("rxnorm", "RxNorm"),
                            ("loinc", "LOINC"),
                            ("dsmv", "DSM-V"),
                            ("ndc", "NDC"),
                            ("hcpcs", "HCPCS"),
                            ("custom", "Custom"),
                        ],
                        help_text="Code system name",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version of the code system", max_length=50
                    ),
                ),
                (
                    "revision_date",
                    models.DateField(
                        help_text="Official revision date of this version"
                    ),
                ),
                (
                    "file_checksum",
                    models.CharField(
                        blank=True,
                        help_text="MD5 checksum of source file",
                        max_length=64,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Source file name", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("installing", "Installing"),
                            ("installed", "Installed"),
                            ("failed", "Installation Failed"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="staged",
                        help_text="Installation status",
                        max_length=20,
                    ),
                ),
                (
                    "imported_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when import was completed",
                        null=True,
                    ),
                ),
                (
                    "import_log",
                    models.TextField(blank=True, help_text="Import process log"),
                ),
                (
                    "records_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of records imported"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this code system version"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_system_versions",
                "ordering": ["-revision_date", "-imported_date"],
                "unique_together": {("system_name", "version")},
            },
        ),
        migrations.CreateModel(
            name="CustomCodeSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Code set name", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(help_text="Code set description")),
                (
                    "prefix",
                    models.CharField(
                        blank=True, help_text="Code prefix", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_code_sets",
            },
        ),
        migrations.CreateModel(
            name="CodeMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source_system",
                    models.CharField(help_text="Source code system", max_length=50),
                ),
                (
                    "source_code",
                    models.CharField(help_text="Source code", max_length=50),
                ),
                (
                    "target_system",
                    models.CharField(help_text="Target code system", max_length=50),
                ),
                (
                    "target_code",
                    models.CharField(help_text="Target code", max_length=50),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("equivalent", "Equivalent"),
                            ("broader", "Broader"),
                            ("narrower", "Narrower"),
                            ("related", "Related"),
                            ("inexact", "Inexact"),
                        ],
                        default="equivalent",
                        help_text="Type of mapping relationship",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Mapping confidence (0.00-1.00)",
                        max_digits=3,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Mapping notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_mappings",
                "indexes": [
                    models.Index(
                        fields=["source_system", "source_code"],
                        name="code_mappin_source__50f8ca_idx",
                    ),
                    models.Index(
                        fields=["target_system", "target_code"],
                        name="code_mappin_target__c3ec64_idx",
                    ),
                ],
                "unique_together": {
                    ("source_system", "source_code", "target_system", "target_code")
                },
            },
        ),
        migrations.CreateModel(
            name="CPTCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        help_text="CPT code (5 digits)",
                        max_length=5,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPT code must be 5 digits", regex="^[0-9]{5}$"
                            )
                        ],
                    ),
                ),
                (
                    "short_description",
                    models.CharField(help_text="Short description", max_length=100),
                ),
                ("long_description", models.TextField(help_text="Full description")),
                (
                    "category",
                    models.CharField(help_text="CPT category", max_length=100),
                ),
                (
                    "modifier_allowed",
                    models.BooleanField(
                        default=True, help_text="Whether modifiers are allowed"
                    ),
                ),
                (
                    "bilateral",
                    models.BooleanField(
                        default=False, help_text="Whether procedure can be bilateral"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        limit_choices_to={"system_name": "cpt"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpt_codes",
                        to="code_systems.codesystemversion",
                    ),
                ),
            ],
            options={
                "db_table": "cpt_codes",
                "indexes": [
                    models.Index(fields=["code"], name="cpt_codes_code_21e521_idx"),
                    models.Index(
                        fields=["category"], name="cpt_codes_categor_9addfe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(help_text="Code value", max_length=50)),
                (
                    "description",
                    models.CharField(help_text="Code description", max_length=255),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Sort order"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="code_systems.customcodeset",
                    ),
                ),
            ],
            options={
                "db_table": "custom_codes",
                "ordering": ["code_set", "sort_order", "code"],
                "unique_together": {("code_set", "code")},
            },
        ),
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ICD-10 code (e.g., F32.1)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid ICD-10 code format",
                                regex="^[A-Z][0-9]{2}(\\.[0-9X]{1,4})?$",
                            )
                        ],
                    ),
                ),
                (
                    "short_description",
                    models.CharField(help_text="Short description", max_length=100),
                ),
                ("long_description", models.TextField(help_text="Full description")),
                (
                    "category",
                    models.CharField(
                        help_text="ICD-10 category (e.g., F32)", max_length=5
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(
                        default=True, help_text="Whether this code is billable"
                    ),
                ),
                (
                    "valid_for_coding",
                    models.BooleanField(
                        default=True, help_text="Whether this code is valid for coding"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        limit_choices_to={"system_name": "icd10"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icd10_codes",
                        to="code_systems.codesystemversion",
                    ),
                ),
            ],
            options={
                "db_table": "icd10_codes",
                "indexes": [
                    models.Index(fields=["code"], name="icd10_codes_code_8fbace_idx"),
                    models.Index(
                        fields=["category"], name="icd10_codes_categor_e05097_idx"
                    ),
                    models.Index(
                        fields=["billable"], name="icd10_codes_billabl_2d9e7e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LOINCCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "loinc_num",
                    models.CharField(
                        help_text="LOINC number", max_length=10, unique=True
                    ),
                ),
                ("component", models.CharField(help_text="Component", max_length=255)),
                ("property", models.CharField(help_text="Property", max_length=100)),
                (
                    "time_aspct",
                    models.CharField(help_text="Time aspect", max_length=100),
                ),
                ("system", models.CharField(help_text="System", max_length=100)),
                ("scale_typ", models.CharField(help_text="Scale type", max_length=100)),
                (
                    "method_typ",
                    models.CharField(
                        blank=True, help_text="Method type", max_length=100
                    ),
                ),
                (
                    "short_name",
                    models.CharField(help_text="Short name", max_length=255),
                ),
                (
                    "long_common_name",
                    models.CharField(
                        blank=True, help_text="Long common name", max_length=255
                    ),
                ),
                ("status", models.CharField(help_text="Status", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        limit_choices_to={"system_name": "loinc"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loinc_codes",
                        to="code_systems.codesystemversion",
                    ),
                ),
            ],
            options={
                "db_table": "loinc_codes",
                "indexes": [
                    models.Index(
                        fields=["loinc_num"], name="loinc_codes_loinc_n_e2553c_idx"
                    ),
                    models.Index(
                        fields=["component"], name="loinc_codes_compone_90a5dd_idx"
                    ),
                    models.Index(
                        fields=["status"], name="loinc_codes_status_097dab_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RxNormConcept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rxcui",
                    models.CharField(
                        help_text="RxNorm concept unique identifier",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "preferred_term",
                    models.CharField(
                        help_text="Preferred term for the concept", max_length=255
                    ),
                ),
                (
                    "tty",
                    models.CharField(
                        help_text="Term type (e.g., SCD, SBD, GPCK)", max_length=20
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Source vocabulary", max_length=20),
                ),
                (
                    "suppress",
                    models.CharField(
                        default="N", help_text="Suppress flag", max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        limit_choices_to={"system_name": "rxnorm"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rxnorm_concepts",
                        to="code_systems.codesystemversion",
                    ),
                ),
            ],
            options={
                "db_table": "rxnorm_concepts",
                "indexes": [
                    models.Index(fields=["rxcui"], name="rxnorm_conc_rxcui_89e44a_idx"),
                    models.Index(fields=["tty"], name="rxnorm_conc_tty_147a86_idx"),
                    models.Index(
                        fields=["suppress"], name="rxnorm_conc_suppres_28bf27_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SNOMEDConcept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "concept_id",
                    models.CharField(
                        help_text="SNOMED CT concept ID", max_length=18, unique=True
                    ),
                ),
                (
                    "fully_specified_name",
                    models.TextField(help_text="Fully specified name"),
                ),
                (
                    "preferred_term",
                    models.CharField(help_text="Preferred term", max_length=255),
                ),
                (
                    "definition",
                    models.TextField(blank=True, help_text="Concept definition"),
                ),
                (
                    "semantic_tag",
                    models.CharField(help_text="Semantic tag", max_length=100),
                ),
                ("module_id", models.CharField(help_text="Module ID", max_length=18)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        limit_choices_to={"system_name": "snomed"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snomed_concepts",
                        to="code_systems.codesystemversion",
                    ),
                ),
            ],
            options={
                "db_table": "snomed_concepts",
                "indexes": [
                    models.Index(
                        fields=["concept_id"], name="snomed_conc_concept_f4a48a_idx"
                    ),
                    models.Index(
                        fields=["semantic_tag"], name="snomed_conc_semanti_877eab_idx"
                    ),
                ],
            },
        ),
    ]
