# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESignConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("forms", "Forms"),
                            ("encounters", "Encounters"),
                            ("documents", "Documents"),
                            ("prescriptions", "Prescriptions"),
                            ("lab_results", "Lab Results"),
                        ],
                        help_text="Module this configuration applies to",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "require_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Whether signatures are required for this module",
                    ),
                ),
                (
                    "auto_lock_on_sign",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to automatically lock objects when signed",
                    ),
                ),
                (
                    "allow_amendments",
                    models.BooleanField(
                        default=True,
                        help_text="Whether amendments are allowed after signing",
                    ),
                ),
                (
                    "signature_validity_days",
                    models.PositiveIntegerField(
                        default=365, help_text="Number of days signatures remain valid"
                    ),
                ),
                (
                    "require_reason_for_amendment",
                    models.BooleanField(
                        default=True, help_text="Whether amendment reason is required"
                    ),
                ),
                (
                    "notify_on_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Send notifications when objects are signed",
                    ),
                ),
                (
                    "notify_on_amendment",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications when amendments are made",
                    ),
                ),
                (
                    "configuration_data",
                    models.JSONField(
                        default=dict, help_text="Additional configuration parameters"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_signers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users allowed to sign in this module",
                        related_name="esign_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ESign Configuration",
                "verbose_name_plural": "ESign Configurations",
                "db_table": "esign_configurations",
            },
        ),
        migrations.CreateModel(
            name="ESignSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the object being signed"
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("signature", "Signature"),
                            ("lock", "Lock"),
                            ("amendment", "Amendment"),
                            ("approval", "Approval"),
                            ("review", "Review"),
                        ],
                        default="signature",
                        help_text="Type of signature action",
                        max_length=20,
                    ),
                ),
                (
                    "is_lock",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this signature locks the object from editing",
                    ),
                ),
                (
                    "datetime_signed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the signature was created",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the signed content", max_length=64
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the signature data", max_length=64
                    ),
                ),
                (
                    "amendment_note",
                    models.TextField(
                        blank=True, help_text="Amendment or signature notes"
                    ),
                ),
                (
                    "signature_data",
                    models.JSONField(
                        default=dict, help_text="Additional signature metadata"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which signature was created",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of object being signed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        help_text="User who created the signature",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="esign_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electronic Signature",
                "verbose_name_plural": "Electronic Signatures",
                "db_table": "esign_signatures",
                "ordering": ["-datetime_signed"],
            },
        ),
        migrations.CreateModel(
            name="ESignAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("sign", "Sign"),
                            ("lock", "Lock"),
                            ("unlock", "Unlock"),
                            ("amend", "Amend"),
                            ("verify", "Verify"),
                            ("export", "Export"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "action_details",
                    models.JSONField(
                        default=dict, help_text="Detailed information about the action"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="esign_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related signature (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="esign.esignsignature",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESign Audit Log",
                "verbose_name_plural": "ESign Audit Logs",
                "db_table": "esign_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ESignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("forms", "Forms"),
                            ("encounters", "Encounters"),
                            ("documents", "Documents"),
                            ("prescriptions", "Prescriptions"),
                            ("lab_results", "Lab Results"),
                        ],
                        help_text="Module this template applies to",
                        max_length=50,
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        default=dict, help_text="Template configuration data"
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        default=list, help_text="List of required fields for signing"
                    ),
                ),
                (
                    "signature_workflow",
                    models.JSONField(
                        default=dict, help_text="Workflow configuration for signatures"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the template",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_esign_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ESign Template",
                "verbose_name_plural": "ESign Templates",
                "db_table": "esign_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="esignsignature",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="esign_signa_content_b27142_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="esignsignature",
            index=models.Index(
                fields=["signer", "datetime_signed"],
                name="esign_signa_signer__c08e12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="esignsignature",
            index=models.Index(
                fields=["is_lock"], name="esign_signa_is_lock_abf49b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esignsignature",
            index=models.Index(
                fields=["signature_type"], name="esign_signa_signatu_22a568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esignauditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="esign_audit_user_id_d05504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esignauditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="esign_audit_action_c1b16d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="esignauditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="esign_audit_content_7823e7_idx",
            ),
        ),
    ]
