# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT"),
                            ("asap", "ASAP"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_info",
                    models.TextField(
                        blank=True, help_text="Clinical indication and relevant history"
                    ),
                ),
                (
                    "diagnosis_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="ICD-10 diagnosis codes"
                    ),
                ),
                ("collection_date", models.DateTimeField(blank=True, null=True)),
                ("collection_location", models.CharField(blank=True, max_length=200)),
                ("collector_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collected", "Collected"),
                            ("received", "Received by Lab"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_notes", models.TextField(blank=True)),
                ("external_order_id", models.CharField(blank=True, max_length=100)),
                ("hl7_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("insurance_coverage", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_orders",
                        to="administration.provider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_orders",
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("specimen_id", models.CharField(blank=True, max_length=50)),
                ("collection_tube", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collected", "Collected"),
                            ("received", "Received"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_order_items",
            },
        ),
        migrations.CreateModel(
            name="LabProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "interface_type",
                    models.CharField(
                        choices=[
                            ("hl7", "HL7 Interface"),
                            ("api", "REST API"),
                            ("ftp", "FTP Upload"),
                            ("manual", "Manual Entry"),
                            ("email", "Email Results"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "hl7_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="HL7 interface configuration",
                    ),
                ),
                ("api_endpoint", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=200)),
                ("lab_license_number", models.CharField(blank=True, max_length=100)),
                (
                    "clia_number",
                    models.CharField(
                        blank=True,
                        help_text="Clinical Laboratory Improvement Amendments number",
                        max_length=20,
                    ),
                ),
                (
                    "average_turnaround_time",
                    models.IntegerField(default=24, help_text="Average TAT in hours"),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_providers",
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="lab_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="laboratory.labprovider"
            ),
        ),
        migrations.CreateModel(
            name="LabMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ORM", "Order Message"),
                            ("ORU", "Result Message"),
                            ("ADT", "Patient Admin"),
                            ("ACK", "Acknowledgment"),
                        ],
                        max_length=10,
                    ),
                ),
                ("raw_message", models.TextField(help_text="Raw HL7 message")),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("external_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "lab_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.labprovider",
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_messages",
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("result_value", models.TextField(help_text="Primary result value")),
                (
                    "result_text",
                    models.TextField(
                        blank=True, help_text="Additional text or interpretation"
                    ),
                ),
                ("units", models.CharField(blank=True, max_length=50)),
                ("reference_range", models.CharField(blank=True, max_length=200)),
                (
                    "abnormal_flag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Normal"),
                            ("L", "Low"),
                            ("H", "High"),
                            ("LL", "Critical Low"),
                            ("HH", "Critical High"),
                            ("A", "Abnormal"),
                            ("AA", "Critical"),
                            (">", "Above Instrument Scale"),
                            ("<", "Below Instrument Scale"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "result_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("preliminary", "Preliminary"),
                            ("final", "Final"),
                            ("corrected", "Corrected"),
                            ("amended", "Amended"),
                        ],
                        default="final",
                        max_length=20,
                    ),
                ),
                ("instrument_id", models.CharField(blank=True, max_length=100)),
                ("technician_id", models.CharField(blank=True, max_length=100)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("pathologist_review", models.BooleanField(default=False)),
                ("pathologist_notes", models.TextField(blank=True)),
                ("external_result_id", models.CharField(blank=True, max_length=100)),
                ("hl7_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="laboratory.laborderitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_lab_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_results",
            },
        ),
        migrations.CreateModel(
            name="LabTestCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="laboratory.labtestcategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lab Test Categories",
                "db_table": "laboratory_test_categories",
            },
        ),
        migrations.CreateModel(
            name="LabTestType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True,
                        help_text="Logical Observation Identifiers Names and Codes",
                        max_length=20,
                    ),
                ),
                (
                    "cpt_code",
                    models.CharField(
                        blank=True,
                        help_text="Current Procedural Terminology code",
                        max_length=20,
                    ),
                ),
                (
                    "snomed_code",
                    models.CharField(
                        blank=True, help_text="SNOMED CT code", max_length=20
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("blood", "Blood"),
                            ("serum", "Serum"),
                            ("plasma", "Plasma"),
                            ("urine", "Urine"),
                            ("stool", "Stool"),
                            ("sputum", "Sputum"),
                            ("csf", "Cerebrospinal Fluid"),
                            ("tissue", "Tissue"),
                            ("swab", "Swab"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specimen_volume",
                    models.CharField(
                        blank=True, help_text="Required specimen volume", max_length=50
                    ),
                ),
                ("collection_instructions", models.TextField(blank=True)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("reference_range_male", models.CharField(blank=True, max_length=200)),
                (
                    "reference_range_female",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "reference_range_pediatric",
                    models.CharField(blank=True, max_length=200),
                ),
                ("critical_low", models.CharField(blank=True, max_length=50)),
                ("critical_high", models.CharField(blank=True, max_length=50)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric"),
                            ("text", "Text"),
                            ("coded", "Coded"),
                            ("binary", "Binary (Positive/Negative)"),
                        ],
                        default="numeric",
                        max_length=20,
                    ),
                ),
                (
                    "possible_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Possible values for coded results",
                    ),
                ),
                (
                    "average_tat",
                    models.IntegerField(
                        default=24, help_text="Average turnaround time in hours"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("requires_fasting", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="laboratory.labtestcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_test_types",
            },
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="laboratory.labtesttype"
            ),
        ),
        migrations.CreateModel(
            name="QualityControlLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "qc_type",
                    models.CharField(
                        choices=[
                            ("calibration", "Calibration"),
                            ("control", "Quality Control"),
                            ("proficiency", "Proficiency Testing"),
                            ("maintenance", "Instrument Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("control_lot", models.CharField(blank=True, max_length=50)),
                ("expected_value", models.CharField(blank=True, max_length=100)),
                ("measured_value", models.CharField(blank=True, max_length=100)),
                ("acceptable_range", models.CharField(blank=True, max_length=100)),
                ("passed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("instrument_id", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.labprovider",
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.labtesttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laboratory_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "laboratory_qc_logs",
            },
        ),
        migrations.AddIndex(
            model_name="labprovider",
            index=models.Index(fields=["name"], name="laboratory__name_e35532_idx"),
        ),
        migrations.AddIndex(
            model_name="labprovider",
            index=models.Index(
                fields=["interface_type"], name="laboratory__interfa_28304d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labprovider",
            index=models.Index(
                fields=["is_preferred"], name="laboratory__is_pref_04038d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["order_number"], name="laboratory__order_n_7ce1f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient"], name="laboratory__patient_ffd897_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["provider"], name="laboratory__provide_2fe7b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["order_date"], name="laboratory__order_d_39e154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status"], name="laboratory__status_d72124_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["priority"], name="laboratory__priorit_41815c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labmessage",
            index=models.Index(
                fields=["message_type"], name="laboratory__message_5b251e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labmessage",
            index=models.Index(
                fields=["processing_status"], name="laboratory__process_1881a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labmessage",
            index=models.Index(
                fields=["created_at"], name="laboratory__created_f66130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labmessage",
            index=models.Index(
                fields=["lab_provider"], name="laboratory__lab_pro_04b447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["order_item"], name="laboratory__order_i_492f13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["result_date"], name="laboratory__result__6cf32c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["abnormal_flag"], name="laboratory__abnorma_e5b8ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["result_status"], name="laboratory__result__767801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["verified_date"], name="laboratory__verifie_3961c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtestcategory",
            index=models.Index(fields=["code"], name="laboratory__code_b6fa2a_idx"),
        ),
        migrations.AddIndex(
            model_name="labtestcategory",
            index=models.Index(fields=["name"], name="laboratory__name_3803d2_idx"),
        ),
        migrations.AddIndex(
            model_name="labtestcategory",
            index=models.Index(
                fields=["sort_order"], name="laboratory__sort_or_1bf599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtesttype",
            index=models.Index(fields=["name"], name="laboratory__name_a449cb_idx"),
        ),
        migrations.AddIndex(
            model_name="labtesttype",
            index=models.Index(
                fields=["loinc_code"], name="laboratory__loinc_c_f0ebd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtesttype",
            index=models.Index(
                fields=["cpt_code"], name="laboratory__cpt_cod_337436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtesttype",
            index=models.Index(
                fields=["category"], name="laboratory__categor_69670b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labtesttype",
            index=models.Index(
                fields=["specimen_type"], name="laboratory__specime_1bcb2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(
                fields=["lab_order"], name="laboratory__lab_ord_fd221d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(
                fields=["test_type"], name="laboratory__test_ty_de39f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(fields=["status"], name="laboratory__status_c00389_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="laborderitem",
            unique_together={("lab_order", "test_type")},
        ),
        migrations.AddIndex(
            model_name="qualitycontrollog",
            index=models.Index(
                fields=["test_type"], name="laboratory__test_ty_b56f0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitycontrollog",
            index=models.Index(
                fields=["qc_type"], name="laboratory__qc_type_f48570_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitycontrollog",
            index=models.Index(
                fields=["created_at"], name="laboratory__created_825fb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualitycontrollog",
            index=models.Index(fields=["passed"], name="laboratory__passed_eef21e_idx"),
        ),
    ]
