# Generated by Django 5.2.4 on 2025-09-05 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('health_screening', "0003_alter_healthscreening_unique_together_and_more"),
        # ("laboratory", "0001_initial"),
        ('patients', "0003_alter_patient_medical_record_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FHIRResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=100, unique=True)),
                ("version_id", models.CharField(default="1", max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("resource_data", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FHIRPatientResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_system",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "identifier_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "fhir_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhir_integration.fhirresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FHIRObservationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loinc_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "loinc_display",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    'health_screening',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health_screening.healthscreening",
                    ),
                ),
                # (
                #     "lab_result",
                #     models.ForeignKey(
                #         blank=True,
                #         null=True,
                #         on_delete=django.db.models.deletion.CASCADE,
                #         to="laboratory.labresult",
                #     ),
                # ),
                (
                    "fhir_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhir_integration.fhirresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="USCDIDataElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uscdi_class",
                    models.CharField(
                        choices=[
                            ("demographics", "Patient Demographics"),
                            ("vital_signs", "Vital Signs"),
                            ("laboratory", "Laboratory"),
                            ("medications", "Medications"),
                            ("allergies", "Allergies and Intolerances"),
                            ("conditions", "Problems"),
                            ("procedures", "Procedures"),
                            ("immunizations", "Immunizations"),
                            ("care_team", "Care Team Members"),
                            ("clinical_notes", "Clinical Notes"),
                            ("provenance", "Provenance"),
                            ("smoking_status", "Smoking Status"),
                            ("pediatric", "Pediatric"),
                            ("health_concerns", "Health Concerns"),
                            ("goals", "Goals"),
                            ("assessments", "Assessments"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_element", models.CharField(max_length=200)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "fhir_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhir_integration.fhirresource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fhirresource",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="fhir_integr_resourc_3bc296_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fhirresource",
            index=models.Index(
                fields=["last_updated"], name="fhir_integr_last_up_b76eba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fhirresource",
            unique_together={("resource_type", "resource_id")},
        ),
        migrations.AlterUniqueTogether(
            name="uscdidataelement",
            unique_together={("uscdi_class", "data_element", "fhir_resource")},
        ),
    ]
