# Generated by Django 5.0.8 on 2026-01-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscdidataelement',
            name='uscdi_class',
            field=models.CharField(choices=[('allergies', 'Allergies and Intolerances'), ('care_plan', 'Care Plan'), ('care_team', 'Care Team Members'), ('clinical_notes', 'Clinical Notes'), ('clinical_tests', 'Clinical Tests'), ('diagnostic_imaging', 'Diagnostic Imaging'), ('encounter_information', 'Encounter Information'), ('facility_information', 'Facility Information'), ('family_health_history', 'Family Health History'), ('goals_and_preferences', 'Goals and Preferences'), ('health_insurance_information', 'Health Insurance Information'), ('health_status_assessments', 'Health Status Assessments'), ('immunizations', 'Immunizations'), ('laboratory', 'Laboratory'), ('medical_devices', 'Medical Devices'), ('medications', 'Medications'), ('orders', 'Orders'), ('patient_demographics', 'Patient Demographics/Information'), ('problems', 'Problems'), ('procedures', 'Procedures'), ('provenance', 'Provenance'), ('vital_signs', 'Vital Signs')], max_length=50),
        ),
    ]
