# Generated by Django 5.0.8 on 2026-06-10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


AUDIT_LOGS_UP_SQL = """
CREATE TABLE IF NOT EXISTS audit_logs (
    id uuid PRIMARY KEY,
    action varchar(50) NOT NULL,
    target_table varchar(100) NOT NULL DEFAULT '',
    target_id uuid NULL,
    ip_address inet NULL,
    user_agent text NOT NULL DEFAULT '',
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor_user_id integer NULL,
    patient_id uuid NULL
);

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_user_id integer NULL;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS patient_id uuid NULL;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_table varchar(100) NOT NULL DEFAULT '';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_id uuid NULL;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS occurred_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'audit_logs' AND column_name = 'table_name'
    ) THEN
        EXECUTE 'UPDATE audit_logs SET target_table = table_name WHERE target_table = '''' AND table_name IS NOT NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'audit_logs' AND column_name = 'user_id'
    ) THEN
        EXECUTE 'UPDATE audit_logs SET actor_user_id = user_id WHERE actor_user_id IS NULL AND user_id IS NOT NULL';
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'audit_logs' AND column_name = 'timestamp'
    ) THEN
        EXECUTE 'UPDATE audit_logs SET occurred_at = "timestamp"';
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS audit_logs_actor_u_a375b1_idx ON audit_logs (actor_user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_patient_099191_idx ON audit_logs (patient_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_action_31f574_idx ON audit_logs (action);
CREATE INDEX IF NOT EXISTS audit_logs_target__24bc47_idx ON audit_logs (target_table, target_id);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_integration', '0002_alter_uscdidataelement_uscdi_class'),
        ('patients', '0007_patientpractitionerlink_practitioner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(AUDIT_LOGS_UP_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('action', models.CharField(max_length=50)),
                        ('target_table', models.CharField(blank=True, default='', max_length=100)),
                        ('target_id', models.UUIDField(blank=True, null=True)),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                        ('user_agent', models.TextField(blank=True, default='')),
                        ('metadata_json', models.JSONField(blank=True, default=dict)),
                        ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                        ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='patients.patient')),
                    ],
                    options={
                        'db_table': 'audit_logs',
                        'db_table_comment': '系統稽核紀錄；保存 create/read/update/delete/export/import/login/ai_analyze 等行為。FHIR 對應：AuditEvent、Provenance。',
                        'indexes': [
                            models.Index(fields=['actor_user', '-occurred_at'], name='audit_logs_actor_u_a375b1_idx'),
                            models.Index(fields=['patient', '-occurred_at'], name='audit_logs_patient_099191_idx'),
                            models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
                            models.Index(fields=['target_table', 'target_id'], name='audit_logs_target__24bc47_idx'),
                        ],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='FHIRResourceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_table', models.CharField(max_length=100)),
                ('local_id', models.UUIDField()),
                ('fhir_resource_type', models.CharField(max_length=100)),
                ('fhir_resource_id', models.CharField(max_length=150)),
                ('profile_url', models.URLField(blank=True, default='', max_length=500)),
                ('fhir_json', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fhir_resource_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_mappings', to='fhir_integration.fhirresource')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhir_resource_mappings', to='patients.patient')),
            ],
            options={
                'db_table': 'fhir_resource_mappings',
                'db_table_comment': '內部 relational schema 到 FHIR R4/US Core resource 的投影對應；保存 profile、FHIR JSON 與同步狀態。FHIR 對應：Provenance。',
                'indexes': [
                    models.Index(fields=['local_table', 'local_id'], name='fhir_resour_local_t_7e9e17_idx'),
                    models.Index(fields=['fhir_resource_type', 'fhir_resource_id'], name='fhir_resour_fhir_re_786702_idx'),
                    models.Index(fields=['patient', 'fhir_resource_type'], name='fhir_resour_patient_e15511_idx'),
                    models.Index(fields=['sync_status'], name='fhir_resour_sync_st_081df8_idx'),
                ],
                'unique_together': {('local_table', 'local_id', 'fhir_resource_type')},
            },
        ),
    ]
