# Generated by Django 5.0.8 on 2026-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_integration', '0004_audit_log_legacy_defaults'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='auditlog',
            table_comment='系統稽核紀錄；保存 create/read/update/delete/export/import/login/disease_risk_assess 等行為。FHIR 對應：AuditEvent、Provenance。',
        ),
    ]
