# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Form Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment Form"),
                            ("screening", "Screening Form"),
                            ("documentation", "Documentation Form"),
                            ("questionnaire", "Questionnaire"),
                            ("scale", "Rating Scale"),
                            ("checklist", "Checklist"),
                            ("soap", "SOAP Note"),
                            ("vitals", "Vital Signs"),
                            ("custom", "Custom Form"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("description", models.TextField()),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for completing the form"
                    ),
                ),
                (
                    "is_standardized",
                    models.BooleanField(
                        default=False, help_text="Is this a standardized clinical form?"
                    ),
                ),
                ("requires_authorization", models.BooleanField(default=False)),
                ("auto_calculate_score", models.BooleanField(default=False)),
                ("scoring_algorithm", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_url",
                    models.URLField(
                        blank=True, help_text="Reference to official documentation"
                    ),
                ),
                ("copyright_info", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to="forms.formcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("code", "version")},
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "submission_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(default=dict, help_text="Form field values"),
                ),
                (
                    "calculated_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Calculated scores and results",
                    ),
                ),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "completion_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="FormReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Patient Report"),
                            ("summary", "Summary Report"),
                            ("trend", "Trend Analysis"),
                            ("comparison", "Comparison Report"),
                            ("population", "Population Analysis"),
                            ("quality", "Quality Metrics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict, help_text="Report filters and criteria"
                    ),
                ),
                ("date_range_start", models.DateField(blank=True, null=True)),
                ("date_range_end", models.DateField(blank=True, null=True)),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("excel", "Excel Spreadsheet"),
                            ("csv", "CSV File"),
                            ("json", "JSON Data"),
                            ("xml", "XML File"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("include_patient_details", models.BooleanField(default=True)),
                ("include_scores", models.BooleanField(default=True)),
                ("include_trends", models.BooleanField(default=False)),
                (
                    "generated_file",
                    models.FileField(blank=True, null=True, upload_to="form_reports/"),
                ),
                ("generation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "templates",
                    models.ManyToManyField(
                        related_name="reports", to="forms.formtemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Form Created"),
                            ("viewed", "Form Viewed"),
                            ("started", "Form Started"),
                            ("saved", "Form Saved (Draft)"),
                            ("submitted", "Form Submitted"),
                            ("reviewed", "Form Reviewed"),
                            ("approved", "Form Approved"),
                            ("rejected", "Form Rejected"),
                            ("modified", "Form Modified"),
                            ("deleted", "Form Deleted"),
                            ("exported", "Form Exported"),
                            ("printed", "Form Printed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional action details"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_audit_logs",
                        to="patients.patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="forms.formsubmission",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="forms.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FormValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "field_dependencies",
                    models.JSONField(
                        default=list, help_text="Fields this rule depends on"
                    ),
                ),
                (
                    "validation_logic",
                    models.TextField(help_text="Validation logic (Python expression)"),
                ),
                ("error_message", models.CharField(max_length=200)),
                ("warning_message", models.CharField(blank=True, max_length=200)),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True, help_text="Prevents submission if failed"
                    ),
                ),
                (
                    "trigger_on_change",
                    models.BooleanField(
                        default=False, help_text="Validate on field change"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="forms.formtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["template", "name"],
            },
        ),
        migrations.CreateModel(
            name="StandardizedAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("gad7", "GAD-7 (Generalized Anxiety Disorder 7-item)"),
                            ("phq9", "PHQ-9 (Patient Health Questionnaire-9)"),
                            ("phq2", "PHQ-2 (Patient Health Questionnaire-2)"),
                            ("mmse", "MMSE (Mini-Mental State Examination)"),
                            ("moca", "MoCA (Montreal Cognitive Assessment)"),
                            (
                                "audit",
                                "AUDIT (Alcohol Use Disorders Identification Test)",
                            ),
                            ("cage", "CAGE Questionnaire"),
                            ("epworth", "Epworth Sleepiness Scale"),
                            ("beck_depression", "Beck Depression Inventory"),
                            ("hamilton_depression", "Hamilton Depression Rating Scale"),
                            ("pain_scale", "Pain Assessment Scale"),
                            ("fall_risk", "Fall Risk Assessment"),
                            ("medication_adherence", "Medication Adherence Scale"),
                            ("quality_of_life", "Quality of Life Assessment"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("reference_citation", models.TextField(blank=True)),
                (
                    "clinical_use",
                    models.TextField(help_text="Clinical applications and use cases"),
                ),
                (
                    "scoring_interpretation",
                    models.JSONField(
                        default=dict, help_text="Score ranges and interpretations"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, help_text="Clinically validated assessment"
                    ),
                ),
                ("validation_studies", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standardized_assessment",
                        to="forms.formtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_type"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "Date and Time"),
                            ("boolean", "Yes/No"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multiple Select"),
                            ("scale", "Rating Scale"),
                            ("file", "File Upload"),
                            ("signature", "Digital Signature"),
                            ("calculated", "Calculated Field"),
                            ("separator", "Section Separator"),
                            ("instruction", "Instruction Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("help_text", models.TextField(blank=True)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("default_value", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("validation_regex", models.CharField(blank=True, max_length=500)),
                ("validation_message", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("css_classes", models.CharField(blank=True, max_length=200)),
                (
                    "show_condition",
                    models.JSONField(
                        blank=True, default=dict, help_text="Conditional display rules"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, default=list, help_text="Options for choice fields"
                    ),
                ),
                ("scale_min", models.IntegerField(blank=True, null=True)),
                ("scale_max", models.IntegerField(blank=True, null=True)),
                ("scale_step", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "scale_labels",
                    models.JSONField(
                        blank=True, default=dict, help_text="Labels for scale endpoints"
                    ),
                ),
                (
                    "calculation_formula",
                    models.TextField(
                        blank=True, help_text="Formula for calculated fields"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="forms.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "display_order", "field_name"],
                "unique_together": {("template", "field_name")},
            },
        ),
    ]
