# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("patient_list", "Patient List"),
                            ("appointment_report", "Appointment Report"),
                            ("financial_report", "Financial Report"),
                            ("clinical_report", "Clinical Report"),
                            ("prescription_report", "Prescription Report"),
                            ("immunization_report", "Immunization Report"),
                            ("custom_report", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sql_query",
                    models.TextField(
                        blank=True, help_text="Custom SQL query for the report"
                    ),
                ),
                (
                    "filters_config",
                    models.JSONField(
                        default=dict, help_text="Configuration for report filters"
                    ),
                ),
                (
                    "columns_config",
                    models.JSONField(
                        default=dict, help_text="Configuration for report columns"
                    ),
                ),
                ("supports_pdf", models.BooleanField(default=True)),
                ("supports_excel", models.BooleanField(default=True)),
                ("supports_csv", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
            },
        ),
        migrations.CreateModel(
            name="ReportFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("custom_name", models.CharField(blank=True, max_length=200)),
                (
                    "saved_parameters",
                    models.JSONField(default=dict, help_text="User's saved parameters"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "report_favorites",
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used for this execution"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time", models.DurationField(blank=True, null=True)),
                ("result_count", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "report_executions",
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("schedule_time", models.TimeField(help_text="Time to run the report")),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="For weekly reports (0=Monday)", null=True
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="For monthly reports", null=True
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Default parameters for scheduled execution",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated email addresses"
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=200)),
                ("email_body", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_execution", models.DateTimeField(blank=True, null=True)),
                ("next_execution", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_reports",
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["report_type"], name="report_temp_report__568538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["is_active"], name="report_temp_is_acti_2cb562_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportfavorite",
            index=models.Index(fields=["user"], name="report_favo_user_id_e52566_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reportfavorite",
            unique_together={("user", "template")},
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["executed_by", "created_at"],
                name="report_exec_execute_640190_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(fields=["status"], name="report_exec_status_c1b883_idx"),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["template", "created_at"], name="report_exec_templat_f95ce4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledreport",
            index=models.Index(
                fields=["is_enabled", "next_execution"],
                name="scheduled_r_is_enab_ebbbe9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledreport",
            index=models.Index(
                fields=["scheduled_by"], name="scheduled_r_schedul_739aa8_idx"
            ),
        ),
    ]
