# Generated by Django 5.0.8 on 2026-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('professional', 'Professional (View A)'), ('patient', 'Patient (View B)')], default='patient', max_length=20, verbose_name='角色'),
        ),
    ]
