# Generated by Django 5.0.8 on 2026-06-10 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('role', models.CharField(default='patient', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': '產品使用者主檔；保存 AllCare365 角色、狀態與 auth_user 對應。FHIR 對應：Practitioner/Patient/RelatedPerson 視角色投影。',
                'indexes': [models.Index(fields=['role', 'status'], name='users_role_bc23be_idx'), models.Index(fields=['organization_name'], name='users_organiz_80c2e4_idx')],
            },
        ),
    ]
