# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="pharmacy.drugcategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drug Categories",
                "db_table": "pharmacy_drug_categories",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(help_text="Brand or trade name", max_length=200),
                ),
                (
                    "generic_name",
                    models.CharField(help_text="Generic/chemical name", max_length=200),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Brand name if different from name",
                        max_length=200,
                    ),
                ),
                (
                    "ndc_number",
                    models.CharField(
                        help_text="National Drug Code", max_length=20, unique=True
                    ),
                ),
                (
                    "upc_code",
                    models.CharField(
                        blank=True, help_text="Universal Product Code", max_length=20
                    ),
                ),
                ("manufacturer_code", models.CharField(blank=True, max_length=50)),
                ("therapeutic_class", models.CharField(blank=True, max_length=100)),
                ("pharmacologic_class", models.CharField(blank=True, max_length=100)),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("liquid", "Liquid"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("spray", "Spray"),
                            ("patch", "Patch"),
                            ("inhaler", "Inhaler"),
                            ("suppository", "Suppository"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="e.g., 500mg, 10mg/ml", max_length=100),
                ),
                ("unit", models.CharField(help_text="mg, ml, g, etc.", max_length=20)),
                ("manufacturer", models.CharField(max_length=200)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "controlled_substance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not Controlled"),
                            ("CI", "Schedule I"),
                            ("CII", "Schedule II"),
                            ("CIII", "Schedule III"),
                            ("CIV", "Schedule IV"),
                            ("CV", "Schedule V"),
                        ],
                        max_length=5,
                    ),
                ),
                ("contraindications", models.TextField(blank=True)),
                ("warnings", models.TextField(blank=True)),
                ("side_effects", models.TextField(blank=True)),
                ("interactions", models.TextField(blank=True)),
                (
                    "reorder_level",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_level",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_wholesale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("discontinued", models.BooleanField(default=False)),
                ("discontinued_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.drugcategory",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_drugs",
            },
        ),
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("clinical_management", models.TextField(blank=True)),
                ("mechanism", models.TextField(blank=True)),
                ("reference_source", models.CharField(blank=True, max_length=200)),
                ("reference_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_drug1",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "drug2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_drug2",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_drug_interactions",
            },
        ),
        migrations.CreateModel(
            name="DrugInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("warehouse", models.CharField(default="Main", max_length=100)),
                ("lot_number", models.CharField(max_length=50)),
                ("expiration_date", models.DateField()),
                (
                    "quantity_on_hand",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_allocated",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.facility",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_drug_inventory",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "prescribed_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_dispensed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="tablets, ml, doses, etc.", max_length=20
                    ),
                ),
                (
                    "refills",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "refills_remaining",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dosage_instructions",
                    models.TextField(help_text="Complete dosage instructions"),
                ),
                (
                    "sig_code",
                    models.CharField(
                        blank=True, help_text="Standardized sig code", max_length=20
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., BID, TID, QID, PRN", max_length=50
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 7 days, 2 weeks", max_length=50
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("topical", "Topical"),
                            ("injection", "Injection"),
                            ("inhalation", "Inhalation"),
                            ("sublingual", "Sublingual"),
                            ("rectal", "Rectal"),
                            ("ophthalmic", "Ophthalmic"),
                            ("otic", "Otic"),
                            ("nasal", "Nasal"),
                            ("transdermal", "Transdermal"),
                        ],
                        default="oral",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("pharmacy", models.CharField(blank=True, max_length=200)),
                ("pharmacy_phone", models.CharField(blank=True, max_length=20)),
                ("dispensed_date", models.DateField(blank=True, null=True)),
                (
                    "indication",
                    models.TextField(blank=True, help_text="Reason for prescription"),
                ),
                ("notes", models.TextField(blank=True)),
                ("e_prescribed", models.BooleanField(default=False)),
                ("dea_number", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharmacy.drug"
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_prescriptions",
                        to="administration.provider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_prescriptions",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("dispensing", "Dispensing"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("return", "Return"),
                            ("destruction", "Destruction"),
                            ("loss", "Loss"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_before", models.IntegerField()),
                ("quantity_change", models.IntegerField()),
                ("quantity_after", models.IntegerField()),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="PO number, prescription ID, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="pharmacy.druginventory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_inventory_transactions",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionRefill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "refill_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("requested_date", models.DateField()),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("dispensed_date", models.DateField(blank=True, null=True)),
                (
                    "quantity_dispensed",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "days_supply",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("dispensed", "Dispensed"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_refills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_records",
                        to="pharmacy.prescription",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_refills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_prescription_refills",
            },
        ),
        migrations.CreateModel(
            name="DrugAllergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allergen",
                    models.CharField(
                        help_text="Drug name or allergen if drug not in system",
                        max_length=200,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life Threatening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reaction_description", models.TextField()),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_allergies",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_allergies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_drug_allergies",
                "indexes": [
                    models.Index(
                        fields=["patient"], name="pharmacy_dr_patient_ca44d4_idx"
                    ),
                    models.Index(
                        fields=["drug"], name="pharmacy_dr_drug_id_befcc7_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="pharmacy_dr_severit_0f207a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="drugcategory",
            index=models.Index(fields=["code"], name="pharmacy_dr_code_49883a_idx"),
        ),
        migrations.AddIndex(
            model_name="drugcategory",
            index=models.Index(fields=["name"], name="pharmacy_dr_name_6fae86_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["ndc_number"], name="pharmacy_dr_ndc_num_83279f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["generic_name"], name="pharmacy_dr_generic_ee2b4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["name"], name="pharmacy_dr_name_276179_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["category"], name="pharmacy_dr_categor_531704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["controlled_substance"], name="pharmacy_dr_control_b8c528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["is_active"], name="pharmacy_dr_is_acti_17d556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["severity"], name="pharmacy_dr_severit_d74415_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["drug1", "drug2"], name="pharmacy_dr_drug1_i_273b94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("drug1", "drug2")},
        ),
        migrations.AddIndex(
            model_name="druginventory",
            index=models.Index(
                fields=["drug", "facility"], name="pharmacy_dr_drug_id_5b8935_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginventory",
            index=models.Index(
                fields=["expiration_date"], name="pharmacy_dr_expirat_95fe7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginventory",
            index=models.Index(
                fields=["quantity_on_hand"], name="pharmacy_dr_quantit_5d2cb8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginventory",
            unique_together={("drug", "facility", "lot_number")},
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "prescribed_date"],
                name="pharmacy_pr_patient_46dd10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["provider"], name="pharmacy_pr_provide_4cd196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["drug"], name="pharmacy_pr_drug_id_f15352_idx"),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["status"], name="pharmacy_pr_status_4dcec2_idx"),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescribed_date"], name="pharmacy_pr_prescri_0f9671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["drug_inventory"], name="pharmacy_in_drug_in_9c22a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_type"], name="pharmacy_in_transac_c35c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["created_at"], name="pharmacy_in_created_7f0d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["prescription"], name="pharmacy_in_prescri_1c687b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionrefill",
            index=models.Index(
                fields=["prescription"], name="pharmacy_pr_prescri_d4a80a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionrefill",
            index=models.Index(
                fields=["requested_date"], name="pharmacy_pr_request_a1b322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionrefill",
            index=models.Index(fields=["status"], name="pharmacy_pr_status_86097c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="prescriptionrefill",
            unique_together={("prescription", "refill_number")},
        ),
    ]
