# Generated by Django 5.0.8 on 2025-10-27 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_alter_patient_medical_record_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientWearableAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(verbose_name="開始時間")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                (
                    "care_unit",
                    models.CharField(blank=True, max_length=100, verbose_name="護理單位"),
                ),
                (
                    "room",
                    models.CharField(blank=True, max_length=50, verbose_name="房間"),
                ),
                ("bed", models.CharField(blank=True, max_length=50, verbose_name="床位")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人員",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wearable_assignments",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者穿戴式裝置分配",
                "verbose_name_plural": "患者穿戴式裝置分配",
                "db_table": "patient_wearable_assignments",
            },
        ),
        migrations.CreateModel(
            name="WearableDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device_id",
                    models.CharField(max_length=50, unique=True, verbose_name="裝置ID"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("continuous_monitor", "連續監護儀"),
                            ("wearable_patch", "可穿戴貼片"),
                            ("smartwatch", "智能手錶"),
                            ("fitness_tracker", "健身追蹤器"),
                            ("medical_sensor", "醫療感測器"),
                        ],
                        max_length=50,
                        verbose_name="裝置類型",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        default="Sotera Wireless", max_length=100, verbose_name="製造商"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="型號")),
                (
                    "serial_number",
                    models.CharField(max_length=100, unique=True, verbose_name="序號"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "使用中"),
                            ("inactive", "未使用"),
                            ("maintenance", "維護中"),
                            ("offline", "離線"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後連線時間"),
                ),
                (
                    "battery_level",
                    models.IntegerField(blank=True, null=True, verbose_name="電池電量(%)"),
                ),
                (
                    "supported_measurements",
                    models.JSONField(default=list, verbose_name="支援的測量項目"),
                ),
                (
                    "sampling_rate",
                    models.IntegerField(default=1, verbose_name="採樣頻率(秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "穿戴式裝置",
                "verbose_name_plural": "穿戴式裝置",
                "db_table": "wearable_devices",
            },
        ),
        migrations.CreateModel(
            name="RealTimeVitalSigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="時間戳記")),
                (
                    "heart_rate",
                    models.FloatField(blank=True, null=True, verbose_name="心率(bpm)"),
                ),
                (
                    "systolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="收縮壓(mmHg)"
                    ),
                ),
                (
                    "diastolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="舒張壓(mmHg)"
                    ),
                ),
                (
                    "mean_arterial_pressure",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="平均動脈壓(mmHg)"
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.FloatField(blank=True, null=True, verbose_name="血氧飽和度(%)"),
                ),
                (
                    "respiration_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="呼吸率(breaths/min)"
                    ),
                ),
                (
                    "skin_temperature",
                    models.FloatField(blank=True, null=True, verbose_name="皮膚溫度(°C)"),
                ),
                (
                    "posture",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="姿態"
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(blank=True, null=True, verbose_name="活動強度"),
                ),
                ("signal_quality", models.JSONField(default=dict, verbose_name="信號品質")),
                (
                    "data_complete",
                    models.BooleanField(default=True, verbose_name="數據完整性"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wearable_integration.patientwearableassignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_vitals",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_measurements",
                        to="wearable_integration.wearabledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "實時生命體徵",
                "verbose_name_plural": "實時生命體徵",
                "db_table": "realtime_vital_signs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeRiskAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "analysis_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析時間"),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("cardiovascular", "心血管風險"),
                            ("respiratory", "呼吸系統風險"),
                            ("fall", "跌倒風險"),
                            ("infection", "感染風險"),
                            ("arrhythmia", "心律不整風險"),
                            ("hypotension", "低血壓風險"),
                            ("hypertension", "高血壓風險"),
                        ],
                        max_length=20,
                        verbose_name="風險類型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "低風險"),
                            ("medium_low", "中低風險"),
                            ("medium", "中等風險"),
                            ("high", "高風險"),
                            ("critical", "危急風險"),
                        ],
                        max_length=20,
                        verbose_name="風險等級",
                    ),
                ),
                ("risk_score", models.FloatField(verbose_name="風險分數")),
                ("risk_percentage", models.FloatField(verbose_name="風險百分比")),
                (
                    "contributing_factors",
                    models.JSONField(default=list, verbose_name="危險因子"),
                ),
                ("recommendations", models.JSONField(default=list, verbose_name="建議")),
                (
                    "alert_triggered",
                    models.BooleanField(default=False, verbose_name="是否觸發警報"),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("improving", "改善中"),
                            ("stable", "穩定"),
                            ("worsening", "惡化中"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="趨勢方向",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="可信度分數"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_risks",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vital_signs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_analysis",
                        to="wearable_integration.realtimevitalsigns",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_analyses",
                        to="wearable_integration.wearabledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "實時風險分析",
                "verbose_name_plural": "實時風險分析",
                "db_table": "realtime_risk_analysis",
                "ordering": ["-analysis_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("critical_vitals", "生命體徵危急"),
                            ("device_disconnected", "設備斷線"),
                            ("high_risk_detected", "高風險檢測"),
                            ("trend_deterioration", "趨勢惡化"),
                            ("missing_data", "數據缺失"),
                        ],
                        max_length=30,
                        verbose_name="警報類型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "危急"),
                        ],
                        max_length=20,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活躍"),
                            ("acknowledged", "已確認"),
                            ("resolved", "已解決"),
                            ("dismissed", "已忽略"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="觸發時間"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="確認時間"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解決時間"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="警報標題")),
                ("message", models.TextField(verbose_name="警報訊息")),
                ("data_snapshot", models.JSONField(default=dict, verbose_name="數據快照")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="realtime_alerts_acknowledged_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認人員",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解決人員",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk_analysis",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="wearable_integration.realtimeriskanalysis",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="wearable_integration.wearabledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "實時警報",
                "verbose_name_plural": "實時警報",
                "db_table": "realtime_alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddField(
            model_name="patientwearableassignment",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_assignments",
                to="wearable_integration.wearabledevice",
            ),
        ),
        migrations.CreateModel(
            name="DataStreamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="會話ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活躍"),
                            ("paused", "暫停"),
                            ("stopped", "停止"),
                            ("error", "錯誤"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始時間"),
                ),
                (
                    "last_data_received",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後接收數據時間"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                (
                    "total_data_points",
                    models.IntegerField(default=0, verbose_name="總數據點數"),
                ),
                (
                    "data_quality_score",
                    models.FloatField(default=100.0, verbose_name="數據品質分數"),
                ),
                (
                    "sampling_interval",
                    models.IntegerField(default=1, verbose_name="採樣間隔(秒)"),
                ),
                (
                    "risk_analysis_enabled",
                    models.BooleanField(default=True, verbose_name="啟用風險分析"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wearable_integration.patientwearableassignment",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sessions",
                        to="wearable_integration.wearabledevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "數據流會話",
                "verbose_name_plural": "數據流會話",
                "db_table": "data_stream_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="realtimevitalsigns",
            index=models.Index(
                fields=["patient", "timestamp"], name="realtime_vi_patient_683581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimevitalsigns",
            index=models.Index(
                fields=["timestamp"], name="realtime_vi_timesta_dd542e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimeriskanalysis",
            index=models.Index(
                fields=["patient", "risk_type", "analysis_timestamp"],
                name="realtime_ri_patient_91b471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimeriskanalysis",
            index=models.Index(
                fields=["risk_level", "alert_triggered"],
                name="realtime_ri_risk_le_63e778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimeriskanalysis",
            index=models.Index(
                fields=["analysis_timestamp"], name="realtime_ri_analysi_80463c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimealert",
            index=models.Index(
                fields=["status", "priority"], name="realtime_al_status_0beccd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimealert",
            index=models.Index(
                fields=["patient", "triggered_at"],
                name="realtime_al_patient_741553_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimealert",
            index=models.Index(
                fields=["triggered_at"], name="realtime_al_trigger_6aab4f_idx"
            ),
        ),
    ]
