# Generated by Django 5.2.4 on 2025-07-23 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0002_patient_deceased_date_patient_deceased_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_name', models.CharField(max_length=100, verbose_name='會話名稱')),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='會話日期')),
                ('status', models.CharField(choices=[('open', '開放中'), ('closed', '已關閉'), ('posted', '已過帳'), ('cancelled', '已取消')], default='open', max_length=20, verbose_name='狀態')),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='總付款金額')),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='總調整金額')),
                ('total_writeoffs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='總沖銷金額')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='關閉時間')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='過帳時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_sessions', to=settings.AUTH_USER_MODEL, verbose_name='處理人員')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR會話',
                'verbose_name_plural': 'AR會話',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='ArActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('payment', '付款'), ('adjustment', '調整'), ('writeoff', '沖銷'), ('refund', '退款'), ('transfer', '轉帳')], max_length=20, verbose_name='活動類型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('reason', models.CharField(choices=[('patient_payment', '患者付款'), ('insurance_payment', '保險給付'), ('admin_adjustment', '管理調整'), ('billing_error', '計費錯誤'), ('uncollectible', '無法收回'), ('charity_care', '慈善醫療'), ('contractual_adjustment', '合約調整'), ('other', '其他')], max_length=50, verbose_name='原因')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '現金'), ('check', '支票'), ('credit_card', '信用卡'), ('debit_card', '金融卡'), ('bank_transfer', '銀行轉帳'), ('insurance', '保險給付'), ('other', '其他')], max_length=20, verbose_name='付款方式')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='參考號碼')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='活動日期')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_activities', to='billing.invoice', verbose_name='計費記錄')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_activities', to='patients.patient', verbose_name='患者')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_activities_processed', to=settings.AUTH_USER_MODEL, verbose_name='處理人員')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('ar_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.arsession', verbose_name='AR會話')),
            ],
            options={
                'verbose_name': 'AR活動',
                'verbose_name_plural': 'AR活動',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.AddIndex(
            model_name='arsession',
            index=models.Index(fields=['provider', '-session_date'], name='billing_ars_provide_ba138d_idx'),
        ),
        migrations.AddIndex(
            model_name='arsession',
            index=models.Index(fields=['status'], name='billing_ars_status_e88e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='aractivity',
            index=models.Index(fields=['ar_session', '-activity_date'], name='billing_ara_ar_sess_f140c5_idx'),
        ),
        migrations.AddIndex(
            model_name='aractivity',
            index=models.Index(fields=['patient', '-activity_date'], name='billing_ara_patient_258ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='aractivity',
            index=models.Index(fields=['activity_type'], name='billing_ara_activit_96fcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='aractivity',
            index=models.Index(fields=['processed_by', '-activity_date'], name='billing_ara_process_712810_idx'),
        ),
    ]
