# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登入時間"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(verbose_name="瀏覽器資訊")),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="登出時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "登入歷史",
                "verbose_name_plural": "登入歷史",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話號碼"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, verbose_name="緊急聯絡人"),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="緊急聯絡人電話"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶個人資料",
                "verbose_name_plural": "用戶個人資料",
            },
        ),
    ]
