# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("office", "Medical Office"),
                            ("urgent_care", "Urgent Care"),
                            ("emergency", "Emergency Room"),
                            ("laboratory", "Laboratory"),
                            ("imaging", "Imaging Center"),
                            ("pharmacy", "Pharmacy"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="USA", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("operating_hours", models.TextField(blank=True)),
                ("services_offered", models.TextField(blank=True)),
                (
                    "administrator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "facilities",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_locked", "Account Locked"),
                            ("account_disabled", "Account Disabled"),
                            ("mfa_required", "MFA Required"),
                            ("mfa_failed", "MFA Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "auth_login_attempts",
                "indexes": [
                    models.Index(
                        fields=["username", "attempt_time"],
                        name="auth_login__usernam_41d22d_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempt_time"],
                        name="auth_login__ip_addr_68f5f1_idx",
                    ),
                    models.Index(
                        fields=["result"], name="auth_login__result_f82145_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("permissions", models.ManyToManyField(to="auth.permission")),
            ],
            options={
                "db_table": "auth_permission_groups",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("license_number", models.CharField(max_length=100, unique=True)),
                (
                    "npi_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("dea_number", models.CharField(blank=True, max_length=20)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("physician", "Physician"),
                            ("nurse", "Nurse"),
                            ("nurse_practitioner", "Nurse Practitioner"),
                            ("physician_assistant", "Physician Assistant"),
                            ("specialist", "Specialist"),
                            ("therapist", "Therapist"),
                            ("technician", "Technician"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("primary_specialty", models.CharField(blank=True, max_length=200)),
                ("secondary_specialty", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("medical_school", models.CharField(blank=True, max_length=200)),
                ("residency", models.CharField(blank=True, max_length=200)),
                ("board_certifications", models.TextField(blank=True)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("is_accepting_patients", models.BooleanField(default=True)),
                ("license_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "providers",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="administration.facility",
                    ),
                ),
                (
                    "head_of_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.provider",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("nurse_practitioner", "Nurse Practitioner"),
                            ("physician_assistant", "Physician Assistant"),
                            ("receptionist", "Receptionist"),
                            ("billing_staff", "Billing Staff"),
                            ("lab_technician", "Lab Technician"),
                            ("pharmacist", "Pharmacist"),
                            ("patient", "Patient"),
                            ("read_only", "Read Only User"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("can_access_patients", models.BooleanField(default=False)),
                ("can_access_appointments", models.BooleanField(default=False)),
                ("can_access_medical_records", models.BooleanField(default=False)),
                ("can_access_billing", models.BooleanField(default=False)),
                ("can_access_pharmacy", models.BooleanField(default=False)),
                ("can_access_laboratory", models.BooleanField(default=False)),
                ("can_access_reports", models.BooleanField(default=False)),
                ("can_access_administration", models.BooleanField(default=False)),
                (
                    "data_access_level",
                    models.CharField(
                        choices=[
                            ("none", "No Access"),
                            ("own", "Own Data Only"),
                            ("department", "Department Data"),
                            ("facility", "Facility Data"),
                            ("all", "All Data"),
                        ],
                        default="own",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
            options={
                "db_table": "auth_roles",
            },
        ),
        migrations.CreateModel(
            name="DataAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
                ("field_name", models.CharField(help_text="模型欄位名稱", max_length=100)),
                ("field_value", models.CharField(help_text="欄位值或變數", max_length=200)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("roles", models.ManyToManyField(to="administration.role")),
            ],
            options={
                "db_table": "auth_data_access_rules",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("logged_out", "Logged Out"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_session_logs",
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("secret_key", models.CharField(blank=True, max_length=32)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_two_factor",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department_restriction",
                    models.ForeignKey(
                        blank=True,
                        help_text="限制存取特定部門",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.department",
                    ),
                ),
                (
                    "facility_restriction",
                    models.ForeignKey(
                        blank=True,
                        help_text="限制存取特定醫療機構",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.facility",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="administration.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_roles",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="金鑰名稱/用途", max_length=100)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list, help_text="API範圍權限")),
                (
                    "ip_whitelist",
                    models.JSONField(blank=True, default=list, help_text="IP白名單"),
                ),
                ("rate_limit", models.IntegerField(default=1000, help_text="每小時請求限制")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_api_keys",
                "indexes": [
                    models.Index(fields=["key"], name="auth_api_ke_key_d99186_idx"),
                    models.Index(
                        fields=["user"], name="auth_api_ke_user_id_67412d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="auth_api_ke_is_acti_3ec908_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("action", models.CharField(max_length=100)),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.CharField(max_length=100)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="audit_logs_table_n_c2f649_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(fields=["name"], name="facilities_name_bf865f_idx"),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["facility_type"], name="facilities_facilit_ab2628_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(
                fields=["license_number"], name="providers_license_fa628b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(
                fields=["npi_number"], name="providers_npi_num_13d5f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(
                fields=["provider_type"], name="providers_provide_2b0409_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "facility")},
        ),
        migrations.AddIndex(
            model_name="sessionlog",
            index=models.Index(
                fields=["user", "login_time"], name="auth_sessio_user_id_792ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionlog",
            index=models.Index(
                fields=["session_key"], name="auth_sessio_session_f4c2c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionlog",
            index=models.Index(
                fields=["is_suspicious"], name="auth_sessio_is_susp_63e733_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="systemsetting",
            unique_together={("category", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "facility_restriction")},
        ),
    ]
