# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="名字")),
                ("last_name", models.CharField(max_length=100, verbose_name="姓氏")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, verbose_name="中間名"),
                ),
                ("date_of_birth", models.DateField(verbose_name="出生日期")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男性"), ("F", "女性"), ("O", "其他"), ("U", "未知")],
                        max_length=1,
                        verbose_name="性別",
                    ),
                ),
                (
                    "phone_home",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話號碼格式：'+999999999'，最多15位數字",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="家用電話",
                    ),
                ),
                (
                    "phone_mobile",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話號碼格式：'+999999999'，最多15位數字",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="手機號碼",
                    ),
                ),
                (
                    "phone_work",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話號碼格式：'+999999999'，最多15位數字",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="工作電話",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="電子郵件"),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=200, verbose_name="地址第一行"),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=200, verbose_name="地址第二行"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="城市"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="州/省"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="郵遞區號"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Taiwan", max_length=100, verbose_name="國家"
                    ),
                ),
                (
                    "medical_record_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="病歷號",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(blank=True, max_length=5, verbose_name="血型"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="緊急聯絡人姓名"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話號碼格式：'+999999999'，最多15位數字",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="緊急聯絡人電話",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="緊急聯絡人關係"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, max_length=200, verbose_name="職業"),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=50, verbose_name="婚姻狀況"),
                ),
                ("additional_notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者",
                "verbose_name_plural": "患者",
                "db_table": 'patients',
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientAllergy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allergen", models.CharField(max_length=200, verbose_name="過敏原")),
                ("reaction", models.TextField(blank=True, verbose_name="過敏反應")),
                (
                    "severity",
                    models.CharField(blank=True, max_length=50, verbose_name="嚴重程度"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者過敏",
                "verbose_name_plural": "患者過敏",
                "db_table": "patient_allergies",
            },
        ),
        migrations.CreateModel(
            name="PatientMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="藥物名稱"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="劑量")),
                ("frequency", models.CharField(max_length=100, verbose_name="頻率")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "prescribing_doctor",
                    models.CharField(blank=True, max_length=200, verbose_name="開處方醫生"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者用藥",
                "verbose_name_plural": "患者用藥",
                "db_table": "patient_medications",
            },
        ),
        migrations.CreateModel(
            name="PatientNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "note_type",
                    models.CharField(
                        default="general", max_length=50, verbose_name="備註類型"
                    ),
                ),
                ("is_private", models.BooleanField(default=False, verbose_name="私人備註")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者備註",
                "verbose_name_plural": "患者備註",
                "db_table": "patient_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientVitals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="身高(cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="體重(kg)",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, null=True, verbose_name="收縮壓"),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True, verbose_name="舒張壓"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="心率"),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="體溫(°C)",
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="呼吸頻率"),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(blank=True, null=True, verbose_name="血氧飽和度(%)"),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="BMI",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="測量時間"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "患者生命體徵",
                "verbose_name_plural": "患者生命體徵",
                "db_table": "patient_vitals",
                "ordering": ["-measurement_date"],
            },
        ),
    ]
