# Generated by Django 5.0.8 on 2025-08-09 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_deceased_date_patient_deceased_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='病歷號'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('medical_record_number',), name='unique_active_medical_record_number'),
        ),
    ]
