# Generated by Django 5.0.8 on 2026-01-14 03:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_medical_record_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedication',
            name='dispense_status',
            field=models.CharField(choices=[('active', '調劑中 (Active)'), ('completed', '已完成 (Completed)'), ('on_hold', '暫停 (On Hold)'), ('stopped', '停止 (Stopped)'), ('unknown', '未知 (Unknown)')], default='active', max_length=20, verbose_name='調劑狀態'),
        ),
        migrations.CreateModel(
            name='AdvanceDirective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('dnr', '拒絕心肺復甦術 (DNR)'), ('living_will', '預立醫療遺囑'), ('polst', '維持生命治療醫囑 (POLST)'), ('power_of_attorney', '醫療委任代理人'), ('other', '其他')], max_length=50, verbose_name='指令類型')),
                ('content', models.TextField(verbose_name='內容/觀察紀錄')),
                ('verified_date', models.DateField(default=django.utils.timezone.now, verbose_name='驗證日期')),
                ('file', models.FileField(blank=True, null=True, upload_to='advance_directives/', verbose_name='掃描文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_directives', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '預立醫療決定',
                'verbose_name_plural': '預立醫療決定',
                'db_table': 'advance_directives',
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='計畫標題')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='計畫類別')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='狀態')),
                ('narrative', models.TextField(verbose_name='計畫敘述/評估')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='預計結束日期')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_care_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '照護計畫',
                'verbose_name_plural': '照護計畫',
                'db_table': 'care_plans',
            },
        ),
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=200, verbose_name='設備名稱')),
                ('udi', models.CharField(max_length=100, verbose_name='單一設備識別碼 (UDI)')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='製造商')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='型號')),
                ('implant_date', models.DateField(blank=True, null=True, verbose_name='植入/啟用日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_devices', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '醫療器材',
                'verbose_name_plural': '醫療器材',
                'db_table': 'medical_devices',
            },
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_type', models.CharField(choices=[('medication', '藥物醫囑'), ('procedure', '處置醫囑'), ('lab', '檢驗醫囑'), ('portable', '可攜式醫療醫囑 (POLST/DNR)'), ('other', '其他')], max_length=50, verbose_name='醫囑類型')),
                ('order_detail', models.TextField(verbose_name='醫囑內容')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開立時間')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='狀態')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='開立醫師')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '醫囑',
                'verbose_name_plural': '醫囑',
                'db_table': 'medical_orders',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='機構名稱')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='機構類型')),
                ('address_line1', models.CharField(max_length=200, verbose_name='地址第一行')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='地址第二行')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('state', models.CharField(max_length=100, verbose_name='州/省')),
                ('postal_code', models.CharField(max_length=20, verbose_name='郵遞區號')),
                ('country', models.CharField(default='Taiwan', max_length=100, verbose_name='國家')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('npi', models.CharField(blank=True, max_length=20, verbose_name='NPI (National Provider Identifier)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '醫療機構',
                'verbose_name_plural': '醫療機構',
                'db_table': 'organizations',
            },
        ),
    ]
