# Generated by Django 5.0.8 on 2026-01-14 04:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientmedication_dispense_status_advancedirective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='unknown', max_length=200, verbose_name='成員姓名')),
                ('identifier', models.CharField(blank=True, default='', max_length=100, verbose_name='識別碼 (Identifier)')),
                ('role', models.CharField(default='provider', max_length=100, verbose_name='角色')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='位置')),
                ('telecom', models.CharField(blank=True, default='', max_length=100, verbose_name='電信聯絡')),
            ],
            options={
                'verbose_name': '醫療團隊成員',
                'db_table': 'care_team_members',
            },
        ),
        migrations.CreateModel(
            name='FamilyHealthHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relationship', models.CharField(max_length=100, verbose_name='與患者關係')),
                ('condition', models.CharField(max_length=200, verbose_name='疾病狀況')),
                ('deceased', models.BooleanField(default=False, verbose_name='是否已故')),
                ('age_of_onset', models.IntegerField(blank=True, null=True, verbose_name='發病年齡')),
            ],
            options={
                'verbose_name': '家族病史',
                'db_table': 'family_health_history',
            },
        ),
        migrations.RemoveField(
            model_name='employerdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employerdata',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='employerdata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='historydata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='advancedirective',
            options={'verbose_name': '預立醫療與偏好'},
        ),
        migrations.AlterModelOptions(
            name='careplan',
            options={'verbose_name': '照護計畫'},
        ),
        migrations.AlterModelOptions(
            name='insurancedata',
            options={'verbose_name': '健康保險信息'},
        ),
        migrations.AlterModelOptions(
            name='medicaldevice',
            options={'verbose_name': '醫療器材'},
        ),
        migrations.AlterModelOptions(
            name='medicalorder',
            options={'verbose_name': '醫囑'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '醫療機構'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者', 'verbose_name_plural': '患者'},
        ),
        migrations.AlterModelOptions(
            name='patientallergy',
            options={'verbose_name': '患者過敏'},
        ),
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'verbose_name': '臨床筆記'},
        ),
        migrations.AlterModelOptions(
            name='patientmedication',
            options={'verbose_name': '患者用藥'},
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_active_medical_record_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='deceased_date',
            new_name='date_of_death',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='interpreter_required',
            new_name='interpreter_needed',
        ),
        migrations.AlterUniqueTogether(
            name='insurancedata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='advancedirective',
            name='content',
        ),
        migrations.RemoveField(
            model_name='advancedirective',
            name='file',
        ),
        migrations.RemoveField(
            model_name='advancedirective',
            name='type',
        ),
        migrations.RemoveField(
            model_name='advancedirective',
            name='verified_date',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='author',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='narrative',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='medicaldevice',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicaldevice',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='medicalorder',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='medicalorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='npi',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deceased_reason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ethnoracial',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='financial_review_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hipaa_mail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hipaa_message',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hipaa_notice',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hipaa_voice',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='language',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_home',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_work',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referrer_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='social_security_number',
        ),
        migrations.RemoveField(
            model_name='patientallergy',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='access_restricted',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='is_confidential',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='prescribing_doctor',
        ),
        migrations.AddField(
            model_name='advancedirective',
            name='advance_directive_observation',
            field=models.TextField(blank=True, verbose_name='預立醫療決定觀察'),
        ),
        migrations.AddField(
            model_name='advancedirective',
            name='care_experience_preference',
            field=models.TextField(blank=True, verbose_name='照護經驗偏好'),
        ),
        migrations.AddField(
            model_name='advancedirective',
            name='patient_goals',
            field=models.TextField(blank=True, verbose_name='患者目標'),
        ),
        migrations.AddField(
            model_name='advancedirective',
            name='sdoh_goals',
            field=models.TextField(blank=True, verbose_name='SDOH 目標'),
        ),
        migrations.AddField(
            model_name='advancedirective',
            name='treatment_intervention_preference',
            field=models.TextField(blank=True, verbose_name='治療介入偏好'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='assessment_and_plan',
            field=models.TextField(default='', verbose_name='評估與治療計畫 (Assessment and Plan of Treatment)'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='care_plan',
            field=models.TextField(default='', verbose_name='照護計畫 (Care Plan)'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='coverage_status',
            field=models.CharField(default='active', max_length=50, verbose_name='覆蓋狀態'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='coverage_type',
            field=models.CharField(default='health', max_length=100, verbose_name='覆蓋類型'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='group_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='群組識別碼'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='member_identifier',
            field=models.CharField(default='unknown', max_length=100, verbose_name='成員識別碼'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='payer_identifier',
            field=models.CharField(default='unknown', max_length=100, verbose_name='付款人識別碼'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='relationship_to_subscriber',
            field=models.CharField(default='self', max_length=50, verbose_name='與訂閱者關係'),
        ),
        migrations.AddField(
            model_name='insurancedata',
            name='subscriber_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='訂閱者識別碼'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='狀態'),
        ),
        migrations.AddField(
            model_name='organization',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='機構識別碼'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='當前地址第一行'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='當前地址第二行'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='電子郵件地址'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, verbose_name='族群'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='姓名後綴'),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation_industry',
            field=models.CharField(blank=True, max_length=200, verbose_name='職業行業'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="電話號碼格式：'+999999999'，最多15位數字", regex='^\\+?1?\\d{9,15}$')], verbose_name='電話號碼'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='電話類型'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(default='zh-tw', max_length=50, verbose_name='偏好語言'),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_address',
            field=models.TextField(blank=True, verbose_name='曾用地址'),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='曾用名'),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, max_length=100, verbose_name='種族'),
        ),
        migrations.AddField(
            model_name='patient',
            name='related_person_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='關聯人姓名'),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='關係類型'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=50, verbose_name='性別 (Sex)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tribal_affiliation',
            field=models.CharField(blank=True, max_length=200, verbose_name='部落隸屬'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='allergy_type',
            field=models.CharField(choices=[('medication', '藥物過敏 (Medication)'), ('drug_class', '藥物類別過敏 (Drug Class)'), ('non_medication', '非藥物過敏 (Non-Medication)')], default='medication', max_length=50, verbose_name='過敏類型'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='substance',
            field=models.CharField(default='unknown', max_length=200, verbose_name='物質 (Substance)'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='content',
            field=models.TextField(default='', verbose_name='內容 (Narrative)'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='note_type',
            field=models.CharField(choices=[('consultation', '諮詢記錄 (Consultation Note)'), ('discharge_summary', '出院摘要 (Discharge Summary)'), ('emergency', '急診記錄 (Emergency Department Note)'), ('history_physical', '病史與體格檢查 (History & Physical)'), ('operative', '手術記錄 (Operative Note)'), ('procedure', '處置記錄 (Procedure Note)'), ('progress', '病程記錄 (Progress Note)')], default='progress', max_length=50, verbose_name='筆記類型'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='dose_unit_of_measure',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='劑量單位'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='indication',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='適應症'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='medication',
            field=models.CharField(default='unknown', max_length=200, verbose_name='藥物 (Medication)'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='medication_adherence',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='遵醫囑情況'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='medication_instructions',
            field=models.TextField(blank=True, default='', verbose_name='用法說明'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='route_of_administration',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='給藥途徑'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='implant_date',
            field=models.DateField(blank=True, null=True, verbose_name='植入日期'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='udi',
            field=models.CharField(max_length=100, verbose_name='唯一設備識別碼 (UDI)'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開立日期'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_detail',
            field=models.TextField(default='', verbose_name='醫囑細節'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_type',
            field=models.CharField(choices=[('medication', '藥物醫囑 (Medication Order)'), ('laboratory', '檢驗醫囑 (Laboratory Order)'), ('diagnostic_imaging', '影像醫囑 (Diagnostic Imaging Order)'), ('clinical_test', '臨床測試醫囑 (Clinical Test Order)'), ('procedure', '處置醫囑 (Procedure Order)'), ('portable', '可攜式醫療醫囑 (Portable Medical Order)')], default='medication', max_length=50, verbose_name='醫囑類型'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line1',
            field=models.CharField(default='', max_length=200, verbose_name='地址第一行'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='地址第二行'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='unknown', max_length=200, verbose_name='機構名稱'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='郵遞區號'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='州/省'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='機構類型'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='中間名 (含首字母)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='reaction',
            field=models.TextField(blank=True, default='', verbose_name='反應 (Reaction)'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='嚴重程度'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dispense_status',
            field=models.CharField(default='active', max_length=50, verbose_name='調劑狀態'),
        ),
        migrations.AlterModelTable(
            name='patientdocument',
            table='clinical_notes',
        ),
        migrations.AddField(
            model_name='careteammember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careteammember',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='careteammember',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyhealthhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyhealthhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='familyhealthhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmployerData',
        ),
        migrations.DeleteModel(
            name='HistoryData',
        ),
        migrations.DeleteModel(
            name='PatientNote',
        ),
        migrations.DeleteModel(
            name='PatientVitals',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='accept_assignment',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='copay',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='deductible',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_address',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_employer',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_first_name',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_last_name',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_middle_name',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_phone',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_relationship',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='subscriber_ss',
        ),
        migrations.RemoveField(
            model_name='insurancedata',
            name='type',
        ),
    ]
