# Generated by Django 5.0.8 on 2026-04-07 04:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_careteammember_familyhealthhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedirective',
            options={'verbose_name': 'Advance Directive'},
        ),
        migrations.AlterModelOptions(
            name='careplan',
            options={'verbose_name': 'Care Plan'},
        ),
        migrations.AlterModelOptions(
            name='careteammember',
            options={'verbose_name': 'Care Team Member'},
        ),
        migrations.AlterModelOptions(
            name='familyhealthhistory',
            options={'verbose_name': 'Family Health History'},
        ),
        migrations.AlterModelOptions(
            name='insurancedata',
            options={'verbose_name': 'Insurance Data'},
        ),
        migrations.AlterModelOptions(
            name='medicaldevice',
            options={'verbose_name': 'Medical Device'},
        ),
        migrations.AlterModelOptions(
            name='medicalorder',
            options={'verbose_name': 'Medical Order'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='patientallergy',
            options={'verbose_name': 'Patient Allergy'},
        ),
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'verbose_name': 'Clinical Note'},
        ),
        migrations.AlterModelOptions(
            name='patientmedication',
            options={'verbose_name': 'Patient Medication'},
        ),
        migrations.AlterField(
            model_name='advancedirective',
            name='advance_directive_observation',
            field=models.TextField(blank=True, verbose_name='Advance Directive Observation'),
        ),
        migrations.AlterField(
            model_name='advancedirective',
            name='care_experience_preference',
            field=models.TextField(blank=True, verbose_name='Care Experience Preference'),
        ),
        migrations.AlterField(
            model_name='advancedirective',
            name='patient_goals',
            field=models.TextField(blank=True, verbose_name='Patient Goals'),
        ),
        migrations.AlterField(
            model_name='advancedirective',
            name='sdoh_goals',
            field=models.TextField(blank=True, verbose_name='SDOH Goals'),
        ),
        migrations.AlterField(
            model_name='advancedirective',
            name='treatment_intervention_preference',
            field=models.TextField(blank=True, verbose_name='Treatment Preference'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='assessment_and_plan',
            field=models.TextField(default='', verbose_name='Assessment and Plan'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='care_plan',
            field=models.TextField(default='', verbose_name='Care Plan'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='name',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='role',
            field=models.CharField(default='provider', max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='telecom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telecom'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='age_of_onset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age of Onset'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='condition',
            field=models.CharField(max_length=200, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='deceased',
            field=models.BooleanField(default=False, verbose_name='Deceased'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='relationship',
            field=models.CharField(max_length=100, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='coverage_status',
            field=models.CharField(default='active', max_length=50, verbose_name='Coverage Status'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='coverage_type',
            field=models.CharField(default='health', max_length=100, verbose_name='Coverage Type'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='group_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Group ID'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='member_identifier',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='payer_identifier',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Payer ID'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='relationship_to_subscriber',
            field=models.CharField(default='self', max_length=50, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='insurancedata',
            name='subscriber_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subscriber ID'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='device_name',
            field=models.CharField(max_length=200, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='implant_date',
            field=models.DateField(blank=True, null=True, verbose_name='Implant Date'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='udi',
            field=models.CharField(max_length=100, verbose_name='UDI'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_detail',
            field=models.TextField(default='', verbose_name='Order Details'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='order_type',
            field=models.CharField(choices=[('medication', 'Medication Order'), ('laboratory', 'Laboratory Order'), ('diagnostic_imaging', 'Imaging Order'), ('clinical_test', 'Clinical Test Order'), ('procedure', 'Procedure Order'), ('portable', 'Portable Medical Order')], default='medication', max_length=50, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line1',
            field=models.CharField(default='', max_length=200, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Taiwan', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Organization Identifier'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Taiwan', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_address_line1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Death'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='interpreter_needed',
            field=models.BooleanField(default=False, verbose_name='Interpreter Needed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MRN'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name Suffix'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation_industry',
            field=models.CharField(blank=True, max_length=200, verbose_name='Occupation Industry'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone format: '+999999999', up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(default='zh-tw', max_length=50, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_address',
            field=models.TextField(blank=True, verbose_name='Previous Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Previous Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, max_length=100, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='related_person_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Related Person Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relationship Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tribal_affiliation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tribal Affiliation'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='allergy_type',
            field=models.CharField(choices=[('medication', 'Medication Allergy'), ('drug_class', 'Drug Class Allergy'), ('non_medication', 'Non-Medication Allergy')], default='medication', max_length=50, verbose_name='Allergy Type'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='reaction',
            field=models.TextField(blank=True, default='', verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='substance',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Substance'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='content',
            field=models.TextField(default='', verbose_name='Narrative'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='note_type',
            field=models.CharField(choices=[('consultation', 'Consultation Note'), ('discharge_summary', 'Discharge Summary'), ('emergency', 'Emergency Department Note'), ('history_physical', 'History & Physical'), ('operative', 'Operative Note'), ('procedure', 'Procedure Note'), ('progress', 'Progress Note')], default='progress', max_length=50, verbose_name='Note Type'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dispense_status',
            field=models.CharField(default='active', max_length=50, verbose_name='Dispense Status'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dose_unit_of_measure',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Dose Unit'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='indication',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Indication'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='medication',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='medication_adherence',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Adherence'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='medication_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='route_of_administration',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
