# Generated by Django 5.0.8 on 2026-06-10 05:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_advancedirective_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPractitionerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('link_type', models.CharField(default='primary_care', max_length=50)),
                ('role', models.CharField(default='primary', max_length=100)),
                ('status', models.CharField(default='active', max_length=50)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('permissions_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'patient_practitioner_links',
                'db_table_comment': '醫病關聯與資料存取授權；保存照護團隊、授權範圍與期間。FHIR 對應：CareTeam、Consent、PractitionerRole。',
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('identifier', models.CharField(blank=True, default='', max_length=100, verbose_name='Practitioner Identifier')),
                ('npi', models.CharField(blank=True, default='', max_length=20, verbose_name='NPI')),
                ('license_number', models.CharField(blank=True, default='', max_length=100, verbose_name='License Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('specialty', models.CharField(blank=True, default='', max_length=150, verbose_name='Specialty')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Status')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'db_table': 'practitioners',
                'db_table_comment': '醫師與醫事人員主檔；保存醫師識別、執照、專科與機構資料。FHIR 對應：Practitioner、PractitionerRole。',
            },
        ),
        migrations.AlterModelTableComment(
            name='careplan',
            table_comment='照護計畫；保存 AI 或醫師建立的追蹤計畫、目標與活動。FHIR 對應：CarePlan。',
        ),
        migrations.AlterModelTableComment(
            name='patient',
            table_comment='病患主檔；保存 EHR/EMR 病患人口學資料與來源系統識別。FHIR 對應：Patient。',
        ),
        migrations.AddField(
            model_name='careplan',
            name='activity_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='category',
            field=models.CharField(default='assess-plan', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='goal_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Goals'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='intent',
            field=models.CharField(default='plan', max_length=50, verbose_name='Intent'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='source_ai_result_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Source AI Result ID'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Imported At'),
        ),
        migrations.AddField(
            model_name='patient',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='patient',
            name='source_record_id',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Source Record ID'),
        ),
        migrations.AddField(
            model_name='patient',
            name='source_system',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Source System'),
        ),
        migrations.AddIndex(
            model_name='careplan',
            index=models.Index(fields=['patient', 'status'], name='care_plans_patient_d6e2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='careplan',
            index=models.Index(fields=['category'], name='care_plans_categor_b15c59_idx'),
        ),
        migrations.AddIndex(
            model_name='careplan',
            index=models.Index(fields=['source_ai_result_id'], name='care_plans_source__fcd80a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['medical_record_number'], name='patients_medical_f25f99_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patients_status_7c14f6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['source_system', 'source_record_id'], name='patients_source__d38a39_idx'),
        ),
        migrations.AddField(
            model_name='patientpractitionerlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientpractitionerlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_links', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientpractitionerlink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='patients.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientpractitionerlink',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='patients.practitioner'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['identifier'], name='practitione_identif_938e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['npi'], name='practitione_npi_7f4838_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['status'], name='practitione_status_0195be_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization'], name='practitione_organiz_0b29a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patientpractitionerlink',
            index=models.Index(fields=['patient', 'status'], name='patient_pra_patient_7a2658_idx'),
        ),
        migrations.AddIndex(
            model_name='patientpractitionerlink',
            index=models.Index(fields=['practitioner', 'status'], name='patient_pra_practit_d43b71_idx'),
        ),
        migrations.AddIndex(
            model_name='patientpractitionerlink',
            index=models.Index(fields=['link_type'], name='patient_pra_link_ty_5a7e31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientpractitionerlink',
            unique_together={('patient', 'practitioner', 'link_type')},
        ),
    ]
