# Generated by Django 5.0.8 on 2026-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientpractitionerlink_practitioner_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='careplan',
            table_comment='照護計畫；保存疾病風險判讀或醫師建立的追蹤計畫、目標與活動。FHIR 對應：CarePlan。',
        ),
    ]
