# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientEducationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("content", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("pdf", "PDF Document"),
                            ("infographic", "Infographic"),
                            ("quiz", "Health Quiz"),
                            ("tool", "Health Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Health"),
                            ("chronic_disease", "Chronic Disease Management"),
                            ("prevention", "Disease Prevention"),
                            ("nutrition", "Nutrition"),
                            ("exercise", "Exercise & Fitness"),
                            ("mental_health", "Mental Health"),
                            ("medication", "Medication Management"),
                            ("emergency", "Emergency Care"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="education_resources/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="education_thumbnails/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "applicable_conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="education_resources",
                        to="medical_records.diagnosis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Education Resource",
                "verbose_name_plural": "Patient Education Resources",
                "ordering": ["-is_featured", "-create_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientHealthReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("medication", "Medication Reminder"),
                            ("appointment", "Appointment Reminder"),
                            ("screening", "Health Screening"),
                            ("vaccination", "Vaccination Due"),
                            ("followup", "Follow-up Care"),
                            ("lifestyle", "Lifestyle Reminder"),
                            ("custom", "Custom Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One Time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("remind_date", models.DateTimeField()),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("next_due", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("send_portal_notification", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reminders",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Reminder",
                "verbose_name_plural": "Health Reminders",
                "ordering": ["remind_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientPortalAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("password_reset_token", models.CharField(blank=True, max_length=255)),
                ("password_reset_expires", models.DateTimeField(blank=True, null=True)),
                ("verification_token", models.CharField(blank=True, max_length=255)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("two_factor_secret", models.CharField(blank=True, max_length=32)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("language_preference", models.CharField(default="en", max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Portal Access",
                "verbose_name_plural": "Patient Portal Accesses",
            },
        ),
        migrations.CreateModel(
            name="PatientPortalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_records", "View Medical Records"),
                            ("view_appointments", "View Appointments"),
                            ("view_prescriptions", "View Prescriptions"),
                            ("view_lab_results", "View Lab Results"),
                            ("send_message", "Send Message"),
                            ("download_document", "Download Document"),
                            ("update_profile", "Update Profile"),
                            ("password_change", "Password Change"),
                            ("failed_login", "Failed Login"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_audit_logs",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Audit Log",
                "verbose_name_plural": "Portal Audit Logs",
                "ordering": ["-create_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientPortalPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("email_appointment_reminders", models.BooleanField(default=True)),
                ("email_lab_results", models.BooleanField(default=True)),
                ("email_prescription_ready", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("sms_appointment_reminders", models.BooleanField(default=False)),
                ("sms_lab_results", models.BooleanField(default=False)),
                ("sms_prescription_ready", models.BooleanField(default=False)),
                ("sms_messages", models.BooleanField(default=False)),
                ("share_with_family", models.BooleanField(default=False)),
                ("allow_research_contact", models.BooleanField(default=False)),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("dashboard_widgets", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_preferences",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Preference",
                "verbose_name_plural": "Portal Preferences",
            },
        ),
        migrations.CreateModel(
            name="PatientPortalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Session",
                "verbose_name_plural": "Portal Sessions",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("appointment", "Appointment Request"),
                            ("prescription", "Prescription Refill"),
                            ("test_results", "Test Results Question"),
                            ("billing", "Billing Question"),
                            ("medical", "Medical Question"),
                            ("urgent", "Urgent Message"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_read_by_patient", models.BooleanField(default=False)),
                ("is_read_by_provider", models.BooleanField(default=False)),
                ("read_by_patient_date", models.DateTimeField(blank=True, null=True)),
                ("read_by_provider_date", models.DateTimeField(blank=True, null=True)),
                ("thread_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="patient_portal.portalmessage",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Message",
                "verbose_name_plural": "Portal Messages",
                "ordering": ["-create_date"],
            },
        ),
        migrations.CreateModel(
            name="PortalMessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="portal_attachments/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="patient_portal.portalmessage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
            },
        ),
        migrations.CreateModel(
            name="PatientFamilyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("family_member_name", models.CharField(max_length=200)),
                ("family_member_email", models.EmailField(max_length=254)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Legal Guardian"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("power_of_attorney", "Power of Attorney"),
                            ("healthcare_proxy", "Healthcare Proxy"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("full", "Full Access"),
                            ("limited", "Limited Access"),
                            ("emergency_only", "Emergency Only"),
                        ],
                        default="limited",
                        max_length=20,
                    ),
                ),
                ("can_view_medical_records", models.BooleanField(default=False)),
                ("can_view_appointments", models.BooleanField(default=True)),
                ("can_view_prescriptions", models.BooleanField(default=False)),
                ("can_view_lab_results", models.BooleanField(default=False)),
                ("can_schedule_appointments", models.BooleanField(default=False)),
                ("can_send_messages", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_access",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Access",
                "verbose_name_plural": "Family Access",
                "unique_together": {("patient", "family_member_email")},
            },
        ),
    ]
