# Generated by Django 5.2.4 on 2025-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='ascvd_10_year_risk_men',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='男性10年ASCVD風險'),
        ),
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='ascvd_10_year_risk_women',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='女性10年ASCVD風險'),
        ),
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='cvd_10_year_risk_men',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='男性10年CVD風險'),
        ),
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='cvd_10_year_risk_women',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='女性10年CVD風險'),
        ),
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='hf_10_year_risk_men',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='男性10年HF風險'),
        ),
        migrations.AddField(
            model_name='cardiovascularriskindex',
            name='hf_10_year_risk_women',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='女性10年HF風險'),
        ),
    ]
