# Generated by Django 5.2.4 on 2025-07-18 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("administered_date", models.DateTimeField()),
                (
                    "administered_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative to administered_by",
                        max_length=255,
                    ),
                ),
                ("amount_administered", models.FloatField(blank=True, null=True)),
                (
                    "amount_administered_unit",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "dose_number",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True, help_text="Route of administration", max_length=100
                    ),
                ),
                (
                    "administration_site",
                    models.CharField(
                        blank=True, help_text="Site of administration", max_length=100
                    ),
                ),
                (
                    "vis_date",
                    models.DateField(
                        blank=True, help_text="Date of VIS Statement", null=True
                    ),
                ),
                ("education_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("partially_completed", "Partially Completed"),
                            ("not_completed", "Not Completed"),
                            ("refused", "Refused"),
                            ("deferred", "Deferred"),
                        ],
                        default="completed",
                        max_length=50,
                    ),
                ),
                (
                    "information_source",
                    models.CharField(
                        choices=[
                            ("new_immunization_record", "New Immunization Record"),
                            (
                                "historical_information_source",
                                "Historical Information Source",
                            ),
                            (
                                "historical_information_birth_certificate",
                                "Historical Information Birth Certificate",
                            ),
                            (
                                "historical_information_school_record",
                                "Historical Information School Record",
                            ),
                            (
                                "historical_information_other_provider",
                                "Historical Information Other Provider",
                            ),
                        ],
                        default="new_immunization_record",
                        max_length=50,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("parental_decision", "Parental Decision"),
                            ("religious_exemption", "Religious Exemption"),
                            ("medical_contraindication", "Medical Contraindication"),
                            ("patient_decision", "Patient Decision"),
                            ("other", "Other"),
                        ],
                        max_length=31,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        help_text="Medical code explaining reason",
                        max_length=31,
                    ),
                ),
                (
                    "reason_description",
                    models.TextField(
                        blank=True, help_text="Human readable description of reason"
                    ),
                ),
                ("added_erroneously", models.BooleanField(default=False)),
                ("external_id", models.CharField(blank=True, max_length=20)),
                (
                    "administered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administered_immunizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordering_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordered_immunizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "immunizations",
                "ordering": ["-administered_date"],
            },
        ),
        migrations.CreateModel(
            name="ImmunizationObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("adverse_event", "Adverse Event"),
                            ("allergic_reaction", "Allergic Reaction"),
                            ("local_reaction", "Local Reaction"),
                            ("systemic_reaction", "Systemic Reaction"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("observation_date", models.DateTimeField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("action_taken", models.TextField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=100)),
                ("reported_to_vaers", models.BooleanField(default=False)),
                ("vaers_id", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "immunization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="immunizations.immunization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "immunization_observations",
                "ordering": ["-observation_date"],
            },
        ),
        migrations.CreateModel(
            name="ImmunizationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "age_group",
                    models.CharField(help_text="Target age group", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "immunization_schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "cvx_code",
                    models.CharField(
                        help_text="CDC CVX Code", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                (
                    "vaccine_type",
                    models.CharField(help_text="Type of vaccine", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_age_days",
                    models.IntegerField(
                        blank=True, help_text="Minimum age in days", null=True
                    ),
                ),
                (
                    "max_age_days",
                    models.IntegerField(
                        blank=True, help_text="Maximum age in days", null=True
                    ),
                ),
                (
                    "doses_required",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "interval_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Interval between doses in days",
                        null=True,
                    ),
                ),
                (
                    "storage_temp_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum storage temperature (°C)",
                        null=True,
                    ),
                ),
                (
                    "storage_temp_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum storage temperature (°C)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vaccines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientImmunizationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("overdue", "Overdue"),
                            ("contraindicated", "Contraindicated"),
                            ("refused", "Refused"),
                            ("deferred", "Deferred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("alert_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("acknowledged_date", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunization_alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immunizations.vaccine",
                    ),
                ),
            ],
            options={
                "db_table": "patient_immunization_alerts",
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="ImmunizationContraindication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "contraindication_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("immune_deficiency", "Immune Deficiency"),
                            ("pregnancy", "Pregnancy"),
                            ("age_restriction", "Age Restriction"),
                            ("medical_condition", "Medical Condition"),
                            ("medication_interaction", "Medication Interaction"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("is_permanent", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("absolute", "Absolute Contraindication"),
                            ("relative", "Relative Contraindication"),
                            ("precaution", "Precaution"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contraindications",
                        to="immunizations.vaccine",
                    ),
                ),
            ],
            options={
                "db_table": "immunization_contraindications",
                "ordering": ["vaccine", "contraindication_type"],
            },
        ),
        migrations.AddField(
            model_name="immunization",
            name="vaccine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="immunizations.vaccine"
            ),
        ),
        migrations.CreateModel(
            name="VaccineLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(max_length=50)),
                ("expiration_date", models.DateField()),
                ("quantity_received", models.IntegerField(default=0)),
                ("quantity_used", models.IntegerField(default=0)),
                ("quantity_wasted", models.IntegerField(default=0)),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="immunizations.vaccine",
                    ),
                ),
            ],
            options={
                "db_table": "vaccine_lots",
                "ordering": ["expiration_date"],
            },
        ),
        migrations.AddField(
            model_name="immunization",
            name="vaccine_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="immunizations.vaccinelot",
            ),
        ),
        migrations.CreateModel(
            name="VaccineManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vaccine_manufacturers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="vaccinelot",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="immunizations.vaccinemanufacturer",
            ),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="immunizations.vaccinemanufacturer",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledVaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "dose_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "recommended_age_days",
                    models.IntegerField(help_text="Recommended age in days"),
                ),
                (
                    "earliest_age_days",
                    models.IntegerField(help_text="Earliest age in days"),
                ),
                (
                    "latest_age_days",
                    models.IntegerField(
                        blank=True, help_text="Latest age in days", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="immunizations.immunizationschedule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immunizations.vaccine",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_vaccinations",
                "ordering": ["recommended_age_days"],
                "unique_together": {("schedule", "vaccine", "dose_number")},
            },
        ),
        migrations.AddIndex(
            model_name="immunization",
            index=models.Index(
                fields=["patient", "administered_date"],
                name="immunizatio_patient_830b39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="immunization",
            index=models.Index(
                fields=["vaccine", "administered_date"],
                name="immunizatio_vaccine_63b6c9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vaccinelot",
            unique_together={("vaccine", "lot_number", "manufacturer")},
        ),
    ]
