# Generated by Django 5.2.4 on 2025-07-23 08:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_deceased_date_patient_deceased_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('encounter_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='看診日期')),
                ('encounter_class', models.CharField(default='ambulatory', max_length=50, verbose_name='看診類別')),
                ('reason', models.CharField(choices=[('routine', '例行檢查'), ('follow_up', '追蹤'), ('emergency', '急診'), ('consultation', '諮詢'), ('procedure', '手術/處置'), ('other', '其他')], default='routine', max_length=50, verbose_name='看診原因')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主訴')),
                ('history_present_illness', models.TextField(blank=True, verbose_name='現病史')),
                ('assessment', models.TextField(blank=True, verbose_name='診斷')),
                ('plan', models.TextField(blank=True, verbose_name='治療計劃')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體溫 (°C)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='脈搏 (次/分)')),
                ('respiration', models.IntegerField(blank=True, null=True, verbose_name='呼吸 (次/分)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='收縮壓')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='舒張壓')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='體重 (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高 (cm)')),
                ('status', models.CharField(choices=[('scheduled', '已排程'), ('in_progress', '進行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '未到診')], default='scheduled', max_length=20, verbose_name='狀態')),
                ('billing_code', models.CharField(blank=True, max_length=20, verbose_name='計費代碼')),
                ('facility', models.CharField(blank=True, max_length=100, verbose_name='機構')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient', verbose_name='病患')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_encounters', to=settings.AUTH_USER_MODEL, verbose_name='醫師')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '看診紀錄',
                'verbose_name_plural': '看診紀錄',
                'ordering': ['-encounter_date'],
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='ICD代碼')),
                ('diagnosis_text', models.CharField(max_length=500, verbose_name='診斷描述')),
                ('diagnosis_type', models.CharField(choices=[('primary', '主要診斷'), ('secondary', '次要診斷'), ('rule_out', '排除診斷'), ('differential', '鑑別診斷')], default='primary', max_length=20, verbose_name='診斷類型')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已確認')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='encounters.encounter', verbose_name='看診紀錄')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '看診診斷',
                'verbose_name_plural': '看診診斷',
                'ordering': ['encounter', 'diagnosis_type'],
            },
        ),
        migrations.CreateModel(
            name='EncounterForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('form_type', models.CharField(choices=[('soap', 'SOAP Notes'), ('physical_exam', '理學檢查'), ('medication', '用藥紀錄'), ('lab_order', '檢驗單'), ('imaging_order', '影像檢查單'), ('prescription', '處方簽'), ('referral', '轉診單'), ('other', '其他')], max_length=50, verbose_name='表單類型')),
                ('form_name', models.CharField(max_length=100, verbose_name='表單名稱')),
                ('form_data', models.JSONField(default=dict, verbose_name='表單資料')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='encounters.encounter', verbose_name='看診紀錄')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '看診表單',
                'verbose_name_plural': '看診表單',
                'ordering': ['encounter', 'form_type'],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-encounter_date'], name='encounters__patient_b7ec05_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['provider', '-encounter_date'], name='encounters__provide_4f5f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='encounters__status_d58071_idx'),
        ),
    ]
